Option Explicit

Dim fso, shell, tempFolder, htaPath, htaFile, logPath
Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

tempFolder = shell.ExpandEnvironmentStrings("%TEMP%")
htaPath = tempFolder & "\AI_Server_Manager.hta"
logPath = tempFolder & "\AI_Server_Manager.log"

Set htaFile = fso.CreateTextFile(htaPath, True)
htaFile.WriteLine "<html>"
htaFile.WriteLine "<head>"
htaFile.WriteLine "  <title>AI Server Manager</title>"
htaFile.WriteLine "  <hta:application id='app' border='thin' caption='yes' maximizebutton='no' minimizebutton='yes' showintaskbar='yes' singleinstance='yes' sysmenu='yes' />"
htaFile.WriteLine "  <style>"
htaFile.WriteLine "    body { font-family: Segoe UI, Arial; margin: 16px; background: #0f1115; color: #e6e6e6; }"
htaFile.WriteLine "    h1 { margin: 0 0 12px 0; font-size: 20px; }"
htaFile.WriteLine "    .row { display: flex; gap: 8px; margin-bottom: 10px; }"
htaFile.WriteLine "    button { background: #2d7dff; color: #fff; border: 0; padding: 8px 12px; border-radius: 6px; cursor: pointer; }"
htaFile.WriteLine "    button.secondary { background: #3a3f4b; }"
htaFile.WriteLine "    button.danger { background: #e5484d; }"
htaFile.WriteLine "    .panel { background: #151a21; padding: 12px; border-radius: 8px; }"
htaFile.WriteLine "    pre { margin: 0; white-space: pre-wrap; }"
htaFile.WriteLine "  </style>"
htaFile.WriteLine "  <script language='VBScript'>"
htaFile.WriteLine "    Dim shell"
htaFile.WriteLine "    Set shell = CreateObject(""WScript.Shell"")"
htaFile.WriteLine "    Dim fso"
htaFile.WriteLine "    Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "    Dim logPath"
htaFile.WriteLine "    logPath = """ & Replace(logPath, "\", "\\") & """"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub LogMessage(msg)"
htaFile.WriteLine "      On Error Resume Next"
htaFile.WriteLine "      Dim logFile"
htaFile.WriteLine "      Set logFile = fso.OpenTextFile(logPath, 8, True)"
htaFile.WriteLine "      logFile.WriteLine Now & "" "" & msg"
htaFile.WriteLine "      logFile.Close"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub RunCmd(cmd)"
htaFile.WriteLine "      shell.Run cmd, 0, False"
htaFile.WriteLine "      If Err.Number <> 0 Then"
htaFile.WriteLine "        LogMessage ""RunCmd error: "" & Err.Description & "" | "" & cmd"
htaFile.WriteLine "        Err.Clear"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Function ExecOut(cmd)"
htaFile.WriteLine "      Dim exec"
htaFile.WriteLine "      Set exec = shell.Exec(cmd)"
htaFile.WriteLine "      ExecOut = exec.StdOut.ReadAll"
htaFile.WriteLine "      If Err.Number <> 0 Then"
htaFile.WriteLine "        LogMessage ""ExecOut error: "" & Err.Description & "" | "" & cmd"
htaFile.WriteLine "        Err.Clear"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Function"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub StartServers()"
htaFile.WriteLine "      RunCmd ""wsl bash -lc """"export OLLAMA_HOST=0.0.0.0:11434; nohup ollama serve > /tmp/ollama.log 2>&1 & sleep 2; cd /mnt/c/Users/johnk/stablediff && nohup bash webui.sh --skip-version-check > /tmp/sd-webui.log 2>&1 & echo Starting servers...;"""""""
htaFile.WriteLine "      UpdateStatus"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub StopServers()"
htaFile.WriteLine "      RunCmd ""wsl bash -lc """"pkill -9 ollama 2>/dev/null; sudo pkill -9 ollama 2>/dev/null; pkill -f webui.sh 2>/dev/null; pkill -f launch.py 2>/dev/null; pkill -f gradio 2>/dev/null;"""""""
htaFile.WriteLine "      UpdateStatus"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub UpdateStatus()"
htaFile.WriteLine "      Dim statusText"
htaFile.WriteLine "      statusText = ExecOut(""wsl bash -lc """"echo OLLAMA=$(pgrep -x ollama >/dev/null && echo RUNNING || echo STOPPED); echo SD_WEBUI=$(pgrep -f webui.sh >/dev/null && echo RUNNING || echo STOPPED);"""""")"
htaFile.WriteLine "      statusText = statusText & ExecOut(""cmd /c powershell -NoProfile -Command """"$c=Get-NetTCPConnection -LocalPort 7862 -ErrorAction SilentlyContinue; if ($c) { 'KOHYA_UI=RUNNING' } else { 'KOHYA_UI=STOPPED' }"""""")"
htaFile.WriteLine "      statusBox.innerText = statusText"
htaFile.WriteLine "      UpdateLog"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub UpdateLog()"
htaFile.WriteLine "      On Error Resume Next"
htaFile.WriteLine "      Dim logText, logFile"
htaFile.WriteLine "      logText = """""
htaFile.WriteLine "      If fso.FileExists(logPath) Then"
htaFile.WriteLine "        Set logFile = fso.OpenTextFile(logPath, 1, False)"
htaFile.WriteLine "        logText = logFile.ReadAll"
htaFile.WriteLine "        logFile.Close"
htaFile.WriteLine "      End If"
htaFile.WriteLine "      logBox.innerText = logText"
htaFile.WriteLine "      If Err.Number <> 0 Then"
htaFile.WriteLine "        Err.Clear"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub OpenSD()"
htaFile.WriteLine "      shell.Run ""http://localhost:7860/"", 1, False"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub OpenOllama()"
htaFile.WriteLine "      shell.Run ""http://localhost:11434/"", 1, False"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub OpenKohyaUI()"
htaFile.WriteLine "      shell.Run ""http://127.0.0.1:7862/"", 1, False"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub OpenKohya()"
htaFile.WriteLine "      Dim kohyaPath"
htaFile.WriteLine "      Dim kohyaDir"
htaFile.WriteLine "      kohyaPath = ""C:\\Users\\johnk\\kohya_ss\\gui-uv.bat"""
htaFile.WriteLine "      If Not fso.FileExists(kohyaPath) Then"
htaFile.WriteLine "        kohyaPath = ""C:\\Users\\johnk\\kohya_ss\\kohya_ss\\gui-uv.bat"""
htaFile.WriteLine "      End If"
htaFile.WriteLine "      If Not fso.FileExists(kohyaPath) Then"
htaFile.WriteLine "        kohyaPath = ""C:\\Users\\johnk\\kohya_ss\\gui.bat"""
htaFile.WriteLine "      End If"
htaFile.WriteLine "      If Not fso.FileExists(kohyaPath) Then"
htaFile.WriteLine "        kohyaPath = ""C:\\Users\\johnk\\kohya_ss\\kohya_ss\\gui.bat"""
htaFile.WriteLine "      End If"
htaFile.WriteLine "      If fso.FileExists(kohyaPath) Then"
htaFile.WriteLine "        LogMessage ""Launching Kohya: "" & kohyaPath"
htaFile.WriteLine "        kohyaDir = fso.GetParentFolderName(kohyaPath)"
htaFile.WriteLine "        Dim cmd"
htaFile.WriteLine "        cmd = ""cmd /k cd /d "" & Chr(34) & kohyaDir & Chr(34) & "" && "" & Chr(34) & kohyaPath & Chr(34)"
htaFile.WriteLine "        shell.Run cmd, 1, False"
htaFile.WriteLine "      Else"
htaFile.WriteLine "        LogMessage ""Kohya not found at either path"""
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub Window_OnLoad()"
htaFile.WriteLine "      UpdateStatus"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine "  </script>"
htaFile.WriteLine "</head>"
htaFile.WriteLine "<body>"
htaFile.WriteLine "  <h1>AI Server Manager</h1>"
htaFile.WriteLine "  <div class='row'>"
htaFile.WriteLine "    <button onclick='StartServers'>Start AI Servers</button>"
htaFile.WriteLine "    <button class='danger' onclick='StopServers'>Stop AI Servers</button>"
htaFile.WriteLine "    <button class='secondary' onclick='UpdateStatus'>Refresh Status</button>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "  <div class='row'>"
htaFile.WriteLine "    <button class='secondary' onclick='OpenSD'>Open Stable Diffusion UI</button>"
htaFile.WriteLine "    <button class='secondary' onclick='OpenKohya'>Open Kohya GUI</button>"
htaFile.WriteLine "    <button class='secondary' onclick='OpenKohyaUI'>Open Kohya UI (7862)</button>"
htaFile.WriteLine "    <button class='secondary' onclick='OpenOllama'>Open Ollama</button>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "  <div class='panel'>"
htaFile.WriteLine "    <pre id='statusBox'>Loading status...</pre>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "  <div class='row' style='margin-top: 10px;'>"
htaFile.WriteLine "    <button class='secondary' onclick='UpdateLog'>Refresh Log</button>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "  <div class='panel'>"
htaFile.WriteLine "    <pre id='logBox'>Log output will appear here...</pre>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "</body>"
htaFile.WriteLine "</html>"
htaFile.Close

shell.Run "mshta.exe """ & htaPath & """", 1, False
