// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_InverseBool.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_InverseBool"/>.
/// Tests boolean value inversion in both Convert and ConvertBack directions.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_InverseBoolTests
{
    private readonly Converter_InverseBool _sut;

    public Converter_InverseBoolTests()
    {
        _sut = new Converter_InverseBool();
    }

    [Fact]
    public void Convert_TrueValue_ReturnsFalse()
    {
        var result = _sut.Convert(true, typeof(bool), null, "en-US");

        result.Should().Be(false);
    }

    [Fact]
    public void Convert_FalseValue_ReturnsTrue()
    {
        var result = _sut.Convert(false, typeof(bool), null, "en-US");

        result.Should().Be(true);
    }

    [Fact]
    public void Convert_NullValue_ReturnsTrue()
    {
        var result = _sut.Convert(null, typeof(bool), null, "en-US");

        result.Should().Be(true);
    }

    [Fact]
    public void Convert_NonBooleanValue_ReturnsTrue()
    {
        var result = _sut.Convert("not a bool", typeof(bool), null, "en-US");

        result.Should().Be(true);
    }

    [Fact]
    public void ConvertBack_TrueValue_ReturnsFalse()
    {
        var result = _sut.ConvertBack(true, typeof(bool), null, "en-US");

        result.Should().Be(false);
    }

    [Fact]
    public void ConvertBack_FalseValue_ReturnsTrue()
    {
        var result = _sut.ConvertBack(false, typeof(bool), null, "en-US");

        result.Should().Be(true);
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsFalse()
    {
        var result = _sut.ConvertBack(null, typeof(bool), null, "en-US");

        result.Should().Be(false);
    }

    [Fact]
    public void ConvertBack_NonBooleanValue_ReturnsFalse()
    {
        var result = _sut.ConvertBack("not a bool", typeof(bool), null, "en-US");

        result.Should().Be(false);
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsOriginalValue()
    {
        var original = true;
        var converted = _sut.Convert(original, typeof(bool), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(bool), null, "en-US");

        convertedBack.Should().Be(original);
    }
}
