// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_LoadNumberToOneBased.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_LoadNumberToOneBased"/>.
/// Tests conversion between zero-based and one-based load numbering.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_LoadNumberToOneBasedTests
{
    private readonly Converter_LoadNumberToOneBased _sut;

    public Converter_LoadNumberToOneBasedTests()
    {
        _sut = new Converter_LoadNumberToOneBased();
    }

    [Theory]
    [InlineData(0, 1)]
    [InlineData(1, 2)]
    [InlineData(5, 6)]
    [InlineData(99, 100)]
    public void Convert_IntValue_AddsOne(int input, int expected)
    {
        var result = _sut.Convert(input, typeof(int), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_NullValue_ReturnsNull()
    {
        var result = _sut.Convert(null, typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void Convert_NonIntValue_ReturnsOriginalValue()
    {
        var result = _sut.Convert("not an int", typeof(int), null, "en-US");

        result.Should().Be("not an int");
    }

    [Theory]
    [InlineData("1", 0)]
    [InlineData("2", 1)]
    [InlineData("6", 5)]
    [InlineData("100", 99)]
    public void ConvertBack_ValidStringValue_SubtractsOne(string input, int expected)
    {
        var result = _sut.ConvertBack(input, typeof(int), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void ConvertBack_InvalidString_ReturnsOriginalValue()
    {
        var result = _sut.ConvertBack("not a number", typeof(int), null, "en-US");

        result.Should().Be("not a number");
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsNull()
    {
        var result = _sut.ConvertBack(null, typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsOriginalValue()
    {
        var original = 5;
        var converted = _sut.Convert(original, typeof(int), null, "en-US");
        var convertedString = converted.ToString();
        var convertedBack = _sut.ConvertBack(convertedString, typeof(int), null, "en-US");

        convertedBack.Should().Be(original);
    }
}
