// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_DoubleToDecimal.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_DoubleToDecimal"/>.
/// Tests two-way conversion between double and decimal types.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_DoubleToDecimalTests
{
    private readonly Converter_DoubleToDecimal _sut;

    public Converter_DoubleToDecimalTests()
    {
        _sut = new Converter_DoubleToDecimal();
    }

    [Theory]
    [InlineData(100.50)]
    [InlineData(0)]
    [InlineData(-50.25)]
    [InlineData(1000.999)]
    public void Convert_DecimalValue_ReturnsDoubleEquivalent(decimal input)
    {
        var result = _sut.Convert(input, typeof(double), null, "en-US");

        result.Should().BeOfType<double>();
        ((double)result).Should().BeApproximately((double)input, 0.0001);
    }

    [Fact]
    public void Convert_NullValue_ReturnsZeroDouble()
    {
        var result = _sut.Convert(null, typeof(double), null, "en-US");

        result.Should().Be(0.0);
    }

    [Fact]
    public void Convert_NonDecimalValue_ReturnsZeroDouble()
    {
        var result = _sut.Convert("not a decimal", typeof(double), null, "en-US");

        result.Should().Be(0.0);
    }

    [Theory]
    [InlineData(100.50)]
    [InlineData(0)]
    [InlineData(-50.25)]
    [InlineData(1000.999)]
    public void ConvertBack_DoubleValue_ReturnsDecimalEquivalent(double input)
    {
        var result = _sut.ConvertBack(input, typeof(decimal), null, "en-US");

        result.Should().BeOfType<decimal>();
        ((decimal)result).Should().Be((decimal)input);
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsZeroDecimal()
    {
        var result = _sut.ConvertBack(null, typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_NonDoubleValue_ReturnsZeroDecimal()
    {
        var result = _sut.ConvertBack("not a double", typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsApproximatelyOriginalValue()
    {
        var original = 42.75m;
        var converted = _sut.Convert(original, typeof(double), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(decimal), null, "en-US");

        ((decimal)convertedBack).Should().Be(original);
    }
}
