// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_PartIDToQualityHoldTextColor.cs
// </auto-generated>

using FluentAssertions;
using Microsoft.UI.Xaml.Media;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_PartIDToQualityHoldTextColor"/>.
/// Tests conversion of Part ID strings to SolidColorBrush for text color highlighting.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_PartIDToQualityHoldTextColorTests
{
    private readonly Converter_PartIDToQualityHoldTextColor _sut;

    public Converter_PartIDToQualityHoldTextColorTests()
    {
        _sut = new Converter_PartIDToQualityHoldTextColor();
    }

    [Fact]
    public void Convert_PartIDWithMMFSR_ReturnsRedTextBrush()
    {
        var result = _sut.Convert("MMFSR05645", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Red);
    }

    [Fact]
    public void Convert_PartIDWithMMCSR_ReturnsRedTextBrush()
    {
        var result = _sut.Convert("MMCSR12345", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Red);
    }

    [Fact]
    public void Convert_PartIDWithMMFSRLowercase_ReturnsRedTextBrush()
    {
        var result = _sut.Convert("mmfsr99999", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Red);
    }

    [Fact]
    public void Convert_PartIDWithMMCSRMixedCase_ReturnsRedTextBrush()
    {
        var result = _sut.Convert("MmCsR00000", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Red);
    }

    [Theory]
    [InlineData("ABC12345")]
    [InlineData("XYZ00000")]
    [InlineData("PART99999")]
    [InlineData("12345678")]
    public void Convert_NormalPartID_ReturnsBlackTextBrush(string partID)
    {
        var result = _sut.Convert(partID, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Black);
    }

    [Fact]
    public void Convert_NullValue_ReturnsBlackTextBrush()
    {
        var result = _sut.Convert(null, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Black);
    }

    [Fact]
    public void Convert_EmptyString_ReturnsBlackTextBrush()
    {
        var result = _sut.Convert(string.Empty, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Black);
    }

    [Fact]
    public void Convert_WhitespaceString_ReturnsBlackTextBrush()
    {
        var result = _sut.Convert("   ", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Black);
    }

    [Fact]
    public void Convert_NonStringValue_ReturnsBlackTextBrush()
    {
        var result = _sut.Convert(12345, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Black);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var action = () => _sut.ConvertBack(new SolidColorBrush(Microsoft.UI.Colors.Red), typeof(string), null, "en-US");

        action.Should().Throw<System.NotImplementedException>();
    }
}
