// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_NullableIntToString.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_NullableIntToString"/>.
/// Tests conversion between nullable integer and string.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_NullableIntToStringTests
{
    private readonly Converter_NullableIntToString _sut;

    public Converter_NullableIntToStringTests()
    {
        _sut = new Converter_NullableIntToString();
    }

    [Theory]
    [InlineData(0, "0")]
    [InlineData(100, "100")]
    [InlineData(-50, "-50")]
    [InlineData(int.MaxValue, "2147483647")]
    [InlineData(int.MinValue, "-2147483648")]
    public void Convert_IntValue_ReturnsStringRepresentation(int input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_NullValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_NonIntValue_ReturnsEmptyString()
    {
        var result = _sut.Convert("not an int", typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Theory]
    [InlineData("0", 0)]
    [InlineData("100", 100)]
    [InlineData("-50", -50)]
    [InlineData("2147483647", int.MaxValue)]
    [InlineData("-2147483648", int.MinValue)]
    public void ConvertBack_ValidStringValue_ReturnsInt(string input, int expected)
    {
        var result = _sut.ConvertBack(input, typeof(int), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void ConvertBack_EmptyString_ReturnsNull()
    {
        var result = _sut.ConvertBack(string.Empty, typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_WhitespaceString_ReturnsNull()
    {
        var result = _sut.ConvertBack("   ", typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_InvalidString_ReturnsNull()
    {
        var result = _sut.ConvertBack("not a number", typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsNull()
    {
        var result = _sut.ConvertBack(null, typeof(int), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsOriginalValue()
    {
        var original = 42;
        var converted = _sut.Convert(original, typeof(string), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(int), null, "en-US");

        convertedBack.Should().Be(original);
    }
}
