// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_BoolToString.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_BoolToString"/>.
/// Tests conversion of boolean values to custom string representations using parameter format "TrueText|FalseText".
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_BoolToStringTests
{
    private readonly Converter_BoolToString _sut;

    public Converter_BoolToStringTests()
    {
        _sut = new Converter_BoolToString();
    }

    [Fact]
    public void Convert_TrueValueWithParameter_ReturnsFirstPartOfParameter()
    {
        var result = _sut.Convert(true, typeof(string), "Yes|No", "en-US");

        result.Should().Be("Yes");
    }

    [Fact]
    public void Convert_FalseValueWithParameter_ReturnsSecondPartOfParameter()
    {
        var result = _sut.Convert(false, typeof(string), "Yes|No", "en-US");

        result.Should().Be("No");
    }

    [Theory]
    [InlineData(true, "Active|Inactive", "Active")]
    [InlineData(false, "Active|Inactive", "Inactive")]
    [InlineData(true, "Enabled|Disabled", "Enabled")]
    [InlineData(false, "Enabled|Disabled", "Disabled")]
    public void Convert_WithVariousParameters_ReturnsCorrectString(bool value, string parameter, string expected)
    {
        var result = _sut.Convert(value, typeof(string), parameter, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_WithoutParameter_ReturnsValueToString()
    {
        var result = _sut.Convert(true, typeof(string), null, "en-US");

        result.Should().Be("True");
    }

    [Fact]
    public void Convert_WithInvalidParameter_ReturnsValueToString()
    {
        var result = _sut.Convert(true, typeof(string), "NoSeparator", "en-US");

        result.Should().Be("True");
    }

    [Fact]
    public void Convert_NonBooleanValue_ReturnsValueToString()
    {
        var result = _sut.Convert("not a bool", typeof(string), "Yes|No", "en-US");

        result.Should().Be("not a bool");
    }

    [Fact]
    public void Convert_NullValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), "Yes|No", "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var act = () => _sut.ConvertBack("Yes", typeof(bool), "Yes|No", "en-US");

        act.Should().Throw<NotImplementedException>();
    }
}
