// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_BooleanToVisibility.cs
// </auto-generated>

using FluentAssertions;
using Microsoft.UI.Xaml;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_BooleanToVisibility"/>.
/// Tests conversion of boolean values to Visibility (Visible/Collapsed) with optional inversion.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_BooleanToVisibilityTests
{
    private readonly Converter_BooleanToVisibility _sut;

    public Converter_BooleanToVisibilityTests()
    {
        _sut = new Converter_BooleanToVisibility();
    }

    [Fact]
    public void Convert_TrueValue_ReturnsVisible()
    {
        var result = _sut.Convert(true, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void Convert_FalseValue_ReturnsCollapsed()
    {
        var result = _sut.Convert(false, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NullValue_ReturnsCollapsed()
    {
        var result = _sut.Convert(null, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NonBooleanValue_ReturnsCollapsed()
    {
        var result = _sut.Convert("not a bool", typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_TrueValueWithInverseParameter_ReturnsCollapsed()
    {
        var result = _sut.Convert(true, typeof(Visibility), "Inverse", "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_FalseValueWithInverseParameter_ReturnsVisible()
    {
        var result = _sut.Convert(false, typeof(Visibility), "Inverse", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Theory]
    [InlineData("inverse")]
    [InlineData("INVERSE")]
    [InlineData("InVeRsE")]
    public void Convert_InverseParameterIsCaseInsensitive_InvertsResult(string inverseParam)
    {
        var result = _sut.Convert(true, typeof(Visibility), inverseParam, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NonInverseParameter_IgnoresParameter()
    {
        var result = _sut.Convert(true, typeof(Visibility), "NotInverse", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var act = () => _sut.ConvertBack(Visibility.Visible, typeof(bool), null, "en-US");

        act.Should().Throw<NotImplementedException>();
    }
}
