// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_EmptyStringToVisibility.cs
// </auto-generated>

using FluentAssertions;
using Microsoft.UI.Xaml;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_EmptyStringToVisibility"/>.
/// Tests conversion of string emptiness to Visibility with optional inversion.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_EmptyStringToVisibilityTests
{
    private readonly Converter_EmptyStringToVisibility _sut;

    public Converter_EmptyStringToVisibilityTests()
    {
        _sut = new Converter_EmptyStringToVisibility();
    }

    [Fact]
    public void Convert_NonEmptyString_ReturnsVisible()
    {
        var result = _sut.Convert("Hello", typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void Convert_EmptyString_ReturnsCollapsed()
    {
        var result = _sut.Convert(string.Empty, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NullString_ReturnsCollapsed()
    {
        var result = _sut.Convert(null, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_WhitespaceString_ReturnsCollapsed()
    {
        var result = _sut.Convert("   ", typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NonEmptyStringWithInverseParameter_ReturnsCollapsed()
    {
        var result = _sut.Convert("Hello", typeof(Visibility), "Inverse", "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_EmptyStringWithInverseParameter_ReturnsVisible()
    {
        var result = _sut.Convert(string.Empty, typeof(Visibility), "Inverse", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Theory]
    [InlineData("inverse")]
    [InlineData("INVERSE")]
    [InlineData("InVeRsE")]
    public void Convert_InverseParameterIsCaseInsensitive_InvertsResult(string inverseParam)
    {
        var result = _sut.Convert("Hello", typeof(Visibility), inverseParam, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NonInverseParameter_IgnoresParameter()
    {
        var result = _sut.Convert("Hello", typeof(Visibility), "NotInverse", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var act = () => _sut.ConvertBack(Visibility.Visible, typeof(string), null, "en-US");

        act.Should().Throw<NotImplementedException>();
    }
}
