// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_StringFormat.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_StringFormat"/>.
/// Tests string formatting with custom format parameters.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_StringFormatTests
{
    private readonly Converter_StringFormat _sut;

    public Converter_StringFormatTests()
    {
        _sut = new Converter_StringFormat();
    }

    [Theory]
    [InlineData("Value: {0}", 42, "Value: 42")]
    [InlineData("Name: {0}", "John", "Name: John")]
    [InlineData("Price: ${0:F2}", 19.99, "Price: $19.99")]
    [InlineData("{0} items", 5, "5 items")]
    public void Convert_WithFormatParameter_ReturnsFormattedString(string format, object value, string expected)
    {
        var result = _sut.Convert(value, typeof(string), format, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_WithoutParameter_ReturnsValueToString()
    {
        var result = _sut.Convert("test value", typeof(string), null, "en-US");

        result.Should().Be("test value");
    }

    [Fact]
    public void Convert_NullValueWithFormat_ReturnsFormattedNull()
    {
        var result = _sut.Convert(null, typeof(string), "Value: {0}", "en-US");

        result.Should().Be("Value: ");
    }

    [Fact]
    public void Convert_NullValueWithoutParameter_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_EmptyStringValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(string.Empty, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var act = () => _sut.ConvertBack("formatted string", typeof(object), "{0}", "en-US");

        act.Should().Throw<NotImplementedException>();
    }
}
