// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_DecimalToInt.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_DecimalToInt"/>.
/// Tests conversion of decimal/double/float values to formatted integer strings.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_DecimalToIntTests
{
    private readonly Converter_DecimalToInt _sut;

    public Converter_DecimalToIntTests()
    {
        _sut = new Converter_DecimalToInt();
    }

    [Theory]
    [InlineData(100.75, "100")]
    [InlineData(1000.50, "1,000")]
    [InlineData(0.99, "0")]
    [InlineData(-50.25, "-50")]
    public void Convert_DecimalValue_ReturnsFormattedIntegerString(decimal input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Theory]
    [InlineData(100.75, "100")]
    [InlineData(1000.50, "1,000")]
    [InlineData(0.99, "0")]
    public void Convert_DoubleValue_ReturnsFormattedIntegerString(double input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Theory]
    [InlineData(100.75f, "100")]
    [InlineData(1000.50f, "1,000")]
    [InlineData(0.99f, "0")]
    public void Convert_FloatValue_ReturnsFormattedIntegerString(float input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_NullValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_NonNumericValue_ReturnsValueToString()
    {
        var result = _sut.Convert("test", typeof(string), null, "en-US");

        result.Should().Be("test");
    }

    [Theory]
    [InlineData("100", 100)]
    [InlineData("1000", 1000)]
    [InlineData("0", 0)]
    [InlineData("-50", -50)]
    public void ConvertBack_ValidStringValue_ReturnsDecimal(string input, decimal expected)
    {
        var result = _sut.ConvertBack(input, typeof(decimal), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void ConvertBack_InvalidString_ReturnsZero()
    {
        var result = _sut.ConvertBack("not a number", typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsZero()
    {
        var result = _sut.ConvertBack(null, typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_EmptyString_ReturnsZero()
    {
        var result = _sut.ConvertBack(string.Empty, typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }
}
