// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_NullableDoubleToString.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_NullableDoubleToString"/>.
/// Tests conversion between nullable double and string with 2 decimal place formatting.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_NullableDoubleToStringTests
{
    private readonly Converter_NullableDoubleToString _sut;

    public Converter_NullableDoubleToStringTests()
    {
        _sut = new Converter_NullableDoubleToString();
    }

    [Theory]
    [InlineData(100.5, "100.50")]
    [InlineData(0.0, "0.00")]
    [InlineData(-50.25, "-50.25")]
    [InlineData(1000.99, "1000.99")]
    public void Convert_DoubleValue_ReturnsFormattedString(double input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void Convert_NullValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_NonDoubleValue_ReturnsEmptyString()
    {
        var result = _sut.Convert("not a double", typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Theory]
    [InlineData("100.50", 100.50)]
    [InlineData("0.00", 0.0)]
    [InlineData("-50.25", -50.25)]
    [InlineData("1000", 1000.0)]
    public void ConvertBack_ValidStringValue_ReturnsDouble(string input, double expected)
    {
        var result = _sut.ConvertBack(input, typeof(double), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void ConvertBack_EmptyString_ReturnsNull()
    {
        var result = _sut.ConvertBack(string.Empty, typeof(double), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_WhitespaceString_ReturnsNull()
    {
        var result = _sut.ConvertBack("   ", typeof(double), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_InvalidString_ReturnsNull()
    {
        var result = _sut.ConvertBack("not a number", typeof(double), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsNull()
    {
        var result = _sut.ConvertBack(null, typeof(double), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsApproximatelyOriginalValue()
    {
        var original = 42.75;
        var converted = _sut.Convert(original, typeof(string), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(double), null, "en-US");

        ((double)convertedBack!).Should().BeApproximately(original, 0.01);
    }
}
