// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_EnumToVisibility.cs
// </auto-generated>

using FluentAssertions;
using Microsoft.UI.Xaml;
using MTM_Receiving_Application.Module_Core.Converters;
using MTM_Receiving_Application.Module_Core.Models.Enums;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_EnumToVisibility"/>.
/// Tests conversion of enum values to Visibility based on parameter matching.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_EnumToVisibilityTests
{
    private readonly Converter_EnumToVisibility _sut;

    public Converter_EnumToVisibilityTests()
    {
        _sut = new Converter_EnumToVisibility();
    }

    [Fact]
    public void Convert_MatchingEnumValue_ReturnsVisible()
    {
        var result = _sut.Convert(Enum_ErrorSeverity.Error, typeof(Visibility), "Error", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void Convert_NonMatchingEnumValue_ReturnsCollapsed()
    {
        var result = _sut.Convert(Enum_ErrorSeverity.Error, typeof(Visibility), "Warning", "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_CaseInsensitiveMatch_ReturnsVisible()
    {
        var result = _sut.Convert(Enum_ErrorSeverity.Error, typeof(Visibility), "error", "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void Convert_NullValue_ReturnsCollapsed()
    {
        var result = _sut.Convert(null, typeof(Visibility), "Error", "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_NullParameter_ReturnsCollapsed()
    {
        var result = _sut.Convert(Enum_ErrorSeverity.Error, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Fact]
    public void Convert_BothNullValueAndParameter_ReturnsCollapsed()
    {
        var result = _sut.Convert(null, typeof(Visibility), null, "en-US");

        result.Should().Be(Visibility.Collapsed);
    }

    [Theory]
    [InlineData("Info")]
    [InlineData("Warning")]
    [InlineData("Error")]
    [InlineData("Critical")]
    public void Convert_VariousEnumValues_MatchCorrectly(string parameterValue)
    {
        var enumValue = Enum.Parse<Enum_ErrorSeverity>(parameterValue);
        var result = _sut.Convert(enumValue, typeof(Visibility), parameterValue, "en-US");

        result.Should().Be(Visibility.Visible);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var act = () => _sut.ConvertBack(Visibility.Visible, typeof(Enum_ErrorSeverity), "Error", "en-US");

        act.Should().Throw<NotImplementedException>();
    }
}
