// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_PartIDToQualityHoldBrush.cs
// </auto-generated>

using FluentAssertions;
using Microsoft.UI.Xaml.Media;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_PartIDToQualityHoldBrush"/>.
/// Tests conversion of Part ID strings to SolidColorBrush for quality hold highlighting.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_PartIDToQualityHoldBrushTests
{
    private readonly Converter_PartIDToQualityHoldBrush _sut;

    public Converter_PartIDToQualityHoldBrushTests()
    {
        _sut = new Converter_PartIDToQualityHoldBrush();
    }

    [Fact]
    public void Convert_PartIDWithMMFSR_ReturnsLightRedBrush()
    {
        var result = _sut.Convert("MMFSR05645", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Windows.UI.Color.FromArgb(255, 255, 230, 230));
    }

    [Fact]
    public void Convert_PartIDWithMMCSR_ReturnsLightRedBrush()
    {
        var result = _sut.Convert("MMCSR12345", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Windows.UI.Color.FromArgb(255, 255, 230, 230));
    }

    [Fact]
    public void Convert_PartIDWithMMFSRLowercase_ReturnsLightRedBrush()
    {
        var result = _sut.Convert("mmfsr99999", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Windows.UI.Color.FromArgb(255, 255, 230, 230));
    }

    [Fact]
    public void Convert_PartIDWithMMCSRMixedCase_ReturnsLightRedBrush()
    {
        var result = _sut.Convert("MmCsR00000", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Windows.UI.Color.FromArgb(255, 255, 230, 230));
    }

    [Theory]
    [InlineData("ABC12345")]
    [InlineData("XYZ00000")]
    [InlineData("PART99999")]
    [InlineData("12345678")]
    public void Convert_NormalPartID_ReturnsTransparentBrush(string partID)
    {
        var result = _sut.Convert(partID, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Transparent);
    }

    [Fact]
    public void Convert_NullValue_ReturnsTransparentBrush()
    {
        var result = _sut.Convert(null, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Transparent);
    }

    [Fact]
    public void Convert_EmptyString_ReturnsTransparentBrush()
    {
        var result = _sut.Convert(string.Empty, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Transparent);
    }

    [Fact]
    public void Convert_WhitespaceString_ReturnsTransparentBrush()
    {
        var result = _sut.Convert("   ", typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Transparent);
    }

    [Fact]
    public void Convert_NonStringValue_ReturnsTransparentBrush()
    {
        var result = _sut.Convert(12345, typeof(SolidColorBrush), null, "en-US");

        var brush = result as SolidColorBrush;
        brush.Should().NotBeNull();
        brush!.Color.Should().Be(Microsoft.UI.Colors.Transparent);
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var action = () => _sut.ConvertBack(new SolidColorBrush(Microsoft.UI.Colors.Red), typeof(string), null, "en-US");

        action.Should().Throw<System.NotImplementedException>();
    }
}
