// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_DecimalToString.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_DecimalToString"/>.
/// Tests two-way conversion between decimal and string, with zero values returning empty string.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_DecimalToStringTests
{
    private readonly Converter_DecimalToString _sut;

    public Converter_DecimalToStringTests()
    {
        _sut = new Converter_DecimalToString();
    }

    [Theory]
    [InlineData(100.50)]
    [InlineData(1000.999)]
    [InlineData(-50.25)]
    [InlineData(0.0001)]
    public void Convert_NonZeroDecimalValue_ReturnsStringRepresentation(decimal input)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().BeOfType<string>();
        var resultString = result as string;
        resultString.Should().NotBeNullOrEmpty();
        decimal.TryParse(resultString, out var parsed).Should().BeTrue();
        parsed.Should().Be(input);
    }

    [Fact]
    public void Convert_ZeroValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(0m, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_NullValue_ReturnsEmptyString()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Fact]
    public void Convert_NonDecimalValue_ReturnsEmptyString()
    {
        var result = _sut.Convert("not a decimal", typeof(string), null, "en-US");

        result.Should().Be(string.Empty);
    }

    [Theory]
    [InlineData("100.50", 100.50)]
    [InlineData("1000", 1000)]
    [InlineData("-50.25", -50.25)]
    public void ConvertBack_ValidStringValue_ReturnsDecimal(string input, decimal expected)
    {
        var result = _sut.ConvertBack(input, typeof(decimal), null, "en-US");

        result.Should().Be(expected);
    }

    [Fact]
    public void ConvertBack_EmptyString_ReturnsZero()
    {
        var result = _sut.ConvertBack(string.Empty, typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_WhitespaceString_ReturnsZero()
    {
        var result = _sut.ConvertBack("   ", typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_InvalidString_ReturnsZero()
    {
        var result = _sut.ConvertBack("not a number", typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsZero()
    {
        var result = _sut.ConvertBack(null, typeof(decimal), null, "en-US");

        result.Should().Be(0m);
    }

    [Fact]
    public void Convert_ThenConvertBack_ReturnsOriginalValue()
    {
        var original = 42.75m;
        var converted = _sut.Convert(original, typeof(string), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(decimal), null, "en-US");

        convertedBack.Should().Be(original);
    }
}
