// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/Converter_IconCodeToGlyph.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="Converter_IconCodeToGlyph"/>.
/// Tests conversion of icon codes (HTML entity and hex formats) to glyph characters.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class Converter_IconCodeToGlyphTests
{
    private readonly Converter_IconCodeToGlyph _sut;

    public Converter_IconCodeToGlyphTests()
    {
        _sut = new Converter_IconCodeToGlyph();
    }

    [Theory]
    [InlineData("&#xE7B8;", "\uE7B8")]
    [InlineData("&#x41;", "A")]
    [InlineData("&#x42;", "B")]
    [InlineData("&#x31;", "1")]
    public void Convert_HtmlEntityFormat_ReturnsGlyphCharacter(string input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Theory]
    [InlineData("E7B8", "\uE7B8")]
    [InlineData("0041", "A")]
    [InlineData("0042", "B")]
    [InlineData("0031", "1")]
    public void Convert_HexFormat_ReturnsGlyphCharacter(string input, string expected)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(expected);
    }

    [Theory]
    [InlineData("A")]
    [InlineData("X")]
    [InlineData("@")]
    public void Convert_SingleCharacter_ReturnsSameCharacter(string input)
    {
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(input);
    }

    [Fact]
    public void Convert_MultiCharacterNonHex_ReturnsOriginalString()
    {
        var input = "ABCD";
        var result = _sut.Convert(input, typeof(string), null, "en-US");

        result.Should().Be(input);
    }

    [Fact]
    public void Convert_NullValue_ReturnsDefaultBoxIcon()
    {
        var result = _sut.Convert(null, typeof(string), null, "en-US");

        result.Should().Be("\uE7B8");
    }

    [Fact]
    public void Convert_EmptyString_ReturnsDefaultBoxIcon()
    {
        var result = _sut.Convert(string.Empty, typeof(string), null, "en-US");

        result.Should().Be("\uE7B8");
    }

    [Fact]
    public void Convert_WhitespaceString_ReturnsDefaultBoxIcon()
    {
        var result = _sut.Convert("   ", typeof(string), null, "en-US");

        result.Should().Be("\uE7B8");
    }

    [Fact]
    public void Convert_InvalidHtmlEntityFormat_ReturnsDefaultBoxIcon()
    {
        var result = _sut.Convert("&#xGGGG;", typeof(string), null, "en-US");

        result.Should().Be("\uE7B8");
    }

    [Fact]
    public void ConvertBack_ThrowsNotImplementedException()
    {
        var action = () => _sut.ConvertBack("test", typeof(string), null, "en-US");

        action.Should().Throw<System.NotImplementedException>();
    }
}
