// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Converters/NullableDoubleToDoubleConverter.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Converters;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Converters;

/// <summary>
/// Unit tests for <see cref="NullableDoubleToDoubleConverter"/>.
/// Tests two-way conversion between double? and double for NumberBox bindings.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Converter")]
[Trait("Module", "Module_Core")]
public class NullableDoubleToDoubleConverterTests
{
    private readonly NullableDoubleToDoubleConverter _sut;

    public NullableDoubleToDoubleConverterTests()
    {
        _sut = new NullableDoubleToDoubleConverter();
    }

    [Theory]
    [InlineData(0.0)]
    [InlineData(100.5)]
    [InlineData(-50.25)]
    [InlineData(double.MaxValue)]
    [InlineData(double.MinValue)]
    [InlineData(double.Epsilon)]
    public void Convert_DoubleValue_ReturnsSameValue(double input)
    {
        var result = _sut.Convert(input, typeof(double), null, "en-US");

        result.Should().Be(input);
    }

    [Fact]
    public void Convert_NullableDoubleValue_ReturnsUnboxedValue()
    {
        double? input = 42.5;
        var result = _sut.Convert(input, typeof(double), null, "en-US");

        result.Should().Be(42.5);
    }

    [Fact]
    public void Convert_NullValue_ReturnsZero()
    {
        var result = _sut.Convert(null, typeof(double), null, "en-US");

        result.Should().Be(0.0);
    }

    [Fact]
    public void Convert_NonDoubleValue_ReturnsZero()
    {
        var result = _sut.Convert("not a double", typeof(double), null, "en-US");

        result.Should().Be(0.0);
    }

    [Fact]
    public void Convert_IntValue_ReturnsZero()
    {
        var result = _sut.Convert(123, typeof(double), null, "en-US");

        result.Should().Be(0.0);
    }

    [Theory]
    [InlineData(0.0)]
    [InlineData(100.5)]
    [InlineData(-50.25)]
    [InlineData(double.MaxValue)]
    [InlineData(double.MinValue)]
    public void ConvertBack_DoubleValue_ReturnsNullableDouble(double input)
    {
        var result = _sut.ConvertBack(input, typeof(double?), null, "en-US");

        var nullableResult = result as double?;
        nullableResult.Should().Be((double?)input);
    }

    [Fact]
    public void ConvertBack_ZeroValue_ReturnsZeroNullableDouble()
    {
        var result = _sut.ConvertBack(0.0, typeof(double?), null, "en-US");

        var nullableResult = result as double?;
        nullableResult.Should().Be(0.0);
    }

    [Fact]
    public void ConvertBack_NullValue_ReturnsNull()
    {
        var result = _sut.ConvertBack(null, typeof(double?), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_NonDoubleValue_ReturnsNull()
    {
        var result = _sut.ConvertBack("not a double", typeof(double?), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void ConvertBack_IntValue_ReturnsNull()
    {
        var result = _sut.ConvertBack(123, typeof(double?), null, "en-US");

        result.Should().BeNull();
    }

    [Fact]
    public void Convert_ThenConvertBack_RoundTripSuccessfully()
    {
        double? original = 42.75;
        var converted = _sut.Convert(original, typeof(double), null, "en-US");
        var convertedBack = _sut.ConvertBack(converted, typeof(double?), null, "en-US") as double?;

        convertedBack.Should().Be(original);
    }

    [Fact]
    public void ConvertBack_ThenConvert_RoundTripSuccessfully()
    {
        double original = 99.99;
        var convertedBack = _sut.ConvertBack(original, typeof(double?), null, "en-US") as double?;
        var converted = _sut.Convert(convertedBack, typeof(double), null, "en-US");

        converted.Should().Be(original);
    }
}
