SELECT PO.ID, V.NAME, POL.PART_ID, P.STOCK_UM, POL.USER_ORDER_QTY, POL.TOTAL_USR_RECD_QTY, POL.UNIT_PRICE, CASE WHEN POL.TOTAL_USR_RECD_QTY < = 0 OR POL.UNIT_PRICE < = 0 THEN 0.0 ELSE EXP ( LOG ( POL.UNIT_PRICE ) + LOG ( POL.TOTAL_USR_RECD_QTY ) ) END, POL.DESIRED_RECV_DATE, POL.PROMISE_DATE, POL.LAST_RECEIVED_DATE, POL.LINE_STATUS, PO.STATUS, PO.ORDER_DATE
FROM PURCHASE_ORDER PO
INNER JOIN PURC_ORDER_LINE POL ON POL.PURC_ORDER_ID = PO.ID
INNER JOIN VENDOR V ON V.ID = PO.VENDOR_ID
LEFT OUTER JOIN PART P ON P.ID = POL.PART_ID
WHERE POL.PART_ID LIKE 'MMC%' AND PO.STATUS NOT IN ( 'C' , 'X' ) AND POL.USER_ORDER_QTY - POL.TOTAL_USR_RECD_QTY > 0 AND POL.DESIRED_RECV_DATE BETWEEN '2026-06-21' AND '2026-06-27' OR PART_ID LIKE '%MMF%' AND POL.LINE_STATUS NOT IN ( 'C' , 'X' ) AND PO.STATUS NOT IN ( 'C' , 'X' ) AND POL.USER_ORDER_QTY - POL.TOTAL_USR_RECD_QTY > 0 AND POL.DESIRED_RECV_DATE BETWEEN '2026-06-21' AND '2026-06-27'
ORDER BY PO.VENDOR_ID, POL.DESIRED_RECV_DATE, POL.PART_ID, POL.LINE_NO;