SELECT 
    PO.ID, 
    PO.VENDOR_ID, 
    V.NAME, 
    POL.LINE_NO, 
    POL.PART_ID, 
    P.DESCRIPTION, 
    POL.USER_ORDER_QTY, 
    POL.TOTAL_USR_RECD_QTY, 
    POL.LAST_RECEIVED_DATE, 
    POL.LINE_STATUS, 
    PO.ORDER_DATE, 
    PO.STATUS
FROM PURCHASE_ORDER PO
INNER JOIN PURC_ORDER_LINE POL ON POL.PURC_ORDER_ID = PO.ID
INNER JOIN VENDOR V ON V.ID = PO.VENDOR_ID
LEFT OUTER JOIN PART P ON P.ID = POL.PART_ID
WHERE POL.PART_ID LIKE 'MMC%'
  AND PO.ORDER_DATE BETWEEN '2026-01-01' AND '2026-06-30'
ORDER BY PO.ID, POL.LINE_NO;
