CREATE
OR REPLACE VIEW view_receiving_history AS
SELECT
    id,
    po_number,
    po_line_number,
    part_id,
    part_description,
    quantity,
    CAST(NULL AS DECIMAL(18, 2)) AS weight_lbs,
    heat,
    transaction_date,
    created_at,
    employee_number,
    user_id,
    load_number,
    initial_location,
    packages_per_load,
    package_type_name,
    weight_per_package,
    coils_on_skid,
    label_number,
    vendor_name,
    po_status,
    po_due_date,
    qty_ordered,
    unit_of_measure,
    remaining_quantity,
    is_non_po_item,
    is_quality_hold_required,
    is_quality_hold_acknowledged,
    quality_hold_restriction_type,
    part_skid_total,
    NULL AS notes,
    'Receiving' AS source_module
FROM
    receiving_history
UNION ALL
SELECT
    id,
    po_number,
    po_line_number,
    part_id,
    part_description,
    quantity,
    weight_quantity AS weight_lbs,
    heat,
    transaction_date,
    COALESCE(received_date, created_at) AS created_at,
    employee_number,
    user_id,
    load_number,
    initial_location,
    packages_per_load,
    package_type_name,
    weight_per_package,
    coils_on_skid,
    label_number,
    vendor_name,
    po_status,
    po_due_date,
    qty_ordered,
    unit_of_measure,
    remaining_quantity,
    is_non_po_item,
    is_quality_hold_required,
    is_quality_hold_acknowledged,
    quality_hold_restriction_type,
    part_skid_total,
    NULL AS notes,
    'Receiving' AS source_module
FROM
    receiving_label_data
ORDER BY
    created_at DESC,
    id DESC;