var searchData=
[
  ['dao_20pattern_20mandatory_0',['DAO Pattern (Mandatory)',['../md__a_g_e_n_t_s.html#autotoc_md13',1,'']]],
  ['dao_5fdunnagecustomfield_20cs_1',['File: Module_Dunnage/Data/Dao_DunnageCustomField.cs',['../md_repomix-output-code-only.html#autotoc_md396',1,'']]],
  ['dao_5fdunnageline_20cs_2',['File: Module_Dunnage/Data/Dao_DunnageLine.cs',['../md_repomix-output-code-only.html#autotoc_md264',1,'']]],
  ['dao_5fdunnageload_20cs_3',['File: Module_Dunnage/Data/Dao_DunnageLoad.cs',['../md_repomix-output-code-only.html#autotoc_md397',1,'']]],
  ['dao_5fdunnageload_5ftests_20cs_4',['File: MTM_Receiving_Application.Tests/Module_Dunnage/Data/Dao_DunnageLoad_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md481',1,'']]],
  ['dao_5fdunnagepart_20cs_5',['File: Module_Dunnage/Data/Dao_DunnagePart.cs',['../md_repomix-output-code-only.html#autotoc_md265',1,'']]],
  ['dao_5fdunnagespec_20cs_6',['File: Module_Dunnage/Data/Dao_DunnageSpec.cs',['../md_repomix-output-code-only.html#autotoc_md266',1,'']]],
  ['dao_5fdunnagetype_20cs_7',['File: Module_Dunnage/Data/Dao_DunnageType.cs',['../md_repomix-output-code-only.html#autotoc_md398',1,'']]],
  ['dao_5fdunnageuserpreference_20cs_8',['File: Module_Dunnage/Data/Dao_DunnageUserPreference.cs',['../md_repomix-output-code-only.html#autotoc_md267',1,'']]],
  ['dao_5finforvisualconnection_20cs_9',['File: Module_Core/Data/InforVisual/Dao_InforVisualConnection.cs',['../md_repomix-output-code-only.html#autotoc_md105',1,'']]],
  ['dao_5finforvisualpart_20cs_10',['File: Module_Core/Data/InforVisual/Dao_InforVisualPart.cs',['../md_repomix-output-code-only.html#autotoc_md106',1,'']]],
  ['dao_5finforvisualpo_20cs_11',['Dao_InforVisualPO cs',['../md_repomix-output-code-only.html#autotoc_md107',1,'File: Module_Core/Data/InforVisual/Dao_InforVisualPO.cs'],['../md_repomix-output-code-only.html#autotoc_md499',1,'File: Module_Routing/Data/Dao_InforVisualPO.cs']]],
  ['dao_5finventorieddunnage_20cs_12',['File: Module_Dunnage/Data/Dao_InventoriedDunnage.cs',['../md_repomix-output-code-only.html#autotoc_md399',1,'']]],
  ['dao_5fpackagetype_20cs_13',['File: Module_Settings/Data/Dao_PackageType.cs',['../md_repomix-output-code-only.html#autotoc_md475',1,'']]],
  ['dao_5fpackagetype_5ftests_20cs_14',['File: MTM_Receiving_Application.Tests/Module_Settings/Data/Dao_PackageType_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md485',1,'']]],
  ['dao_5fpackagetypemappings_20cs_15',['File: Module_Settings/Data/Dao_PackageTypeMappings.cs',['../md_repomix-output-code-only.html#autotoc_md437',1,'']]],
  ['dao_5fpackagetypepreference_20cs_16',['File: Module_Receiving/Data/Dao_PackageTypePreference.cs',['../md_repomix-output-code-only.html#autotoc_md287',1,'']]],
  ['dao_5freceivingline_20cs_17',['File: Module_Receiving/Data/Dao_ReceivingLine.cs',['../md_repomix-output-code-only.html#autotoc_md410',1,'']]],
  ['dao_5freceivingline_5ftests_20cs_18',['File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLine_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md482',1,'']]],
  ['dao_5freceivingload_20cs_19',['File: Module_Receiving/Data/Dao_ReceivingLoad.cs',['../md_repomix-output-code-only.html#autotoc_md288',1,'']]],
  ['dao_5freceivingload_5ftests_20cs_20',['File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLoad_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md483',1,'']]],
  ['dao_5freporting_20cs_21',['File: Module_Reporting/Data/Dao_Reporting.cs',['../md_repomix-output-code-only.html#autotoc_md469',1,'']]],
  ['dao_5froutinglabel_20cs_22',['File: Module_Routing/Data/Dao_RoutingLabel.cs',['../md_repomix-output-code-only.html#autotoc_md489',1,'']]],
  ['dao_5froutinglabel_5ftests_20cs_23',['File: MTM_Receiving_Application.Tests/Module_Routing/Data/Dao_RoutingLabel_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md484',1,'']]],
  ['dao_5froutinglabelhistory_20cs_24',['File: Module_Routing/Data/Dao_RoutingLabelHistory.cs',['../md_repomix-output-code-only.html#autotoc_md490',1,'']]],
  ['dao_5froutingotherreason_20cs_25',['File: Module_Routing/Data/Dao_RoutingOtherReason.cs',['../md_repomix-output-code-only.html#autotoc_md424',1,'']]],
  ['dao_5froutingrecipient_20cs_26',['File: Module_Routing/Data/Dao_RoutingRecipient.cs',['../md_repomix-output-code-only.html#autotoc_md307',1,'']]],
  ['dao_5froutingrule_20cs_27',['File: Module_Settings/Data/Dao_RoutingRule.cs',['../md_repomix-output-code-only.html#autotoc_md476',1,'']]],
  ['dao_5froutingusagetracking_20cs_28',['File: Module_Routing/Data/Dao_RoutingUsageTracking.cs',['../md_repomix-output-code-only.html#autotoc_md425',1,'']]],
  ['dao_5froutinguserpreference_20cs_29',['File: Module_Routing/Data/Dao_RoutingUserPreference.cs',['../md_repomix-output-code-only.html#autotoc_md426',1,'']]],
  ['dao_5fscheduledreport_20cs_30',['File: Module_Settings/Data/Dao_ScheduledReport.cs',['../md_repomix-output-code-only.html#autotoc_md438',1,'']]],
  ['dao_5fsettingsauditlog_20cs_31',['File: Module_Settings/Data/Dao_SettingsAuditLog.cs',['../md_repomix-output-code-only.html#autotoc_md477',1,'']]],
  ['dao_5fsystemsettings_20cs_32',['File: Module_Settings/Data/Dao_SystemSettings.cs',['../md_repomix-output-code-only.html#autotoc_md439',1,'']]],
  ['dao_5fuser_20cs_33',['File: Module_Core/Data/Authentication/Dao_User.cs',['../md_repomix-output-code-only.html#autotoc_md509',1,'']]],
  ['dao_5fuser_5ftests_20cs_34',['File: MTM_Receiving_Application.Tests/Module_Core/Data/Authentication/Dao_User_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md480',1,'']]],
  ['dao_5fusersettings_20cs_35',['File: Module_Settings/Data/Dao_UserSettings.cs',['../md_repomix-output-code-only.html#autotoc_md440',1,'']]],
  ['dao_5fvolvopart_20cs_36',['File: Module_Volvo/Data/Dao_VolvoPart.cs',['../md_repomix-output-code-only.html#autotoc_md493',1,'']]],
  ['dao_5fvolvopartcomponent_20cs_37',['File: Module_Volvo/Data/Dao_VolvoPartComponent.cs',['../md_repomix-output-code-only.html#autotoc_md478',1,'']]],
  ['dao_5fvolvosettings_20cs_38',['File: Module_Volvo/Data/Dao_VolvoSettings.cs',['../md_repomix-output-code-only.html#autotoc_md494',1,'']]],
  ['dao_5fvolvoshipment_20cs_39',['File: Module_Volvo/Data/Dao_VolvoShipment.cs',['../md_repomix-output-code-only.html#autotoc_md503',1,'']]],
  ['dao_5fvolvoshipmentline_20cs_40',['File: Module_Volvo/Data/Dao_VolvoShipmentLine.cs',['../md_repomix-output-code-only.html#autotoc_md495',1,'']]],
  ['data_20authentication_20dao_5fuser_20cs_41',['File: Module_Core/Data/Authentication/Dao_User.cs',['../md_repomix-output-code-only.html#autotoc_md509',1,'']]],
  ['data_20authentication_20dao_5fuser_5ftests_20cs_42',['File: MTM_Receiving_Application.Tests/Module_Core/Data/Authentication/Dao_User_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md480',1,'']]],
  ['data_20dao_5fdunnagecustomfield_20cs_43',['File: Module_Dunnage/Data/Dao_DunnageCustomField.cs',['../md_repomix-output-code-only.html#autotoc_md396',1,'']]],
  ['data_20dao_5fdunnageline_20cs_44',['File: Module_Dunnage/Data/Dao_DunnageLine.cs',['../md_repomix-output-code-only.html#autotoc_md264',1,'']]],
  ['data_20dao_5fdunnageload_20cs_45',['File: Module_Dunnage/Data/Dao_DunnageLoad.cs',['../md_repomix-output-code-only.html#autotoc_md397',1,'']]],
  ['data_20dao_5fdunnageload_5ftests_20cs_46',['File: MTM_Receiving_Application.Tests/Module_Dunnage/Data/Dao_DunnageLoad_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md481',1,'']]],
  ['data_20dao_5fdunnagepart_20cs_47',['File: Module_Dunnage/Data/Dao_DunnagePart.cs',['../md_repomix-output-code-only.html#autotoc_md265',1,'']]],
  ['data_20dao_5fdunnagespec_20cs_48',['File: Module_Dunnage/Data/Dao_DunnageSpec.cs',['../md_repomix-output-code-only.html#autotoc_md266',1,'']]],
  ['data_20dao_5fdunnagetype_20cs_49',['File: Module_Dunnage/Data/Dao_DunnageType.cs',['../md_repomix-output-code-only.html#autotoc_md398',1,'']]],
  ['data_20dao_5fdunnageuserpreference_20cs_50',['File: Module_Dunnage/Data/Dao_DunnageUserPreference.cs',['../md_repomix-output-code-only.html#autotoc_md267',1,'']]],
  ['data_20dao_5finforvisualpo_20cs_51',['File: Module_Routing/Data/Dao_InforVisualPO.cs',['../md_repomix-output-code-only.html#autotoc_md499',1,'']]],
  ['data_20dao_5finventorieddunnage_20cs_52',['File: Module_Dunnage/Data/Dao_InventoriedDunnage.cs',['../md_repomix-output-code-only.html#autotoc_md399',1,'']]],
  ['data_20dao_5fpackagetype_20cs_53',['File: Module_Settings/Data/Dao_PackageType.cs',['../md_repomix-output-code-only.html#autotoc_md475',1,'']]],
  ['data_20dao_5fpackagetype_5ftests_20cs_54',['File: MTM_Receiving_Application.Tests/Module_Settings/Data/Dao_PackageType_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md485',1,'']]],
  ['data_20dao_5fpackagetypemappings_20cs_55',['File: Module_Settings/Data/Dao_PackageTypeMappings.cs',['../md_repomix-output-code-only.html#autotoc_md437',1,'']]],
  ['data_20dao_5fpackagetypepreference_20cs_56',['File: Module_Receiving/Data/Dao_PackageTypePreference.cs',['../md_repomix-output-code-only.html#autotoc_md287',1,'']]],
  ['data_20dao_5freceivingline_20cs_57',['File: Module_Receiving/Data/Dao_ReceivingLine.cs',['../md_repomix-output-code-only.html#autotoc_md410',1,'']]],
  ['data_20dao_5freceivingline_5ftests_20cs_58',['File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLine_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md482',1,'']]],
  ['data_20dao_5freceivingload_20cs_59',['File: Module_Receiving/Data/Dao_ReceivingLoad.cs',['../md_repomix-output-code-only.html#autotoc_md288',1,'']]],
  ['data_20dao_5freceivingload_5ftests_20cs_60',['File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLoad_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md483',1,'']]],
  ['data_20dao_5freporting_20cs_61',['File: Module_Reporting/Data/Dao_Reporting.cs',['../md_repomix-output-code-only.html#autotoc_md469',1,'']]],
  ['data_20dao_5froutinglabel_20cs_62',['File: Module_Routing/Data/Dao_RoutingLabel.cs',['../md_repomix-output-code-only.html#autotoc_md489',1,'']]],
  ['data_20dao_5froutinglabel_5ftests_20cs_63',['File: MTM_Receiving_Application.Tests/Module_Routing/Data/Dao_RoutingLabel_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md484',1,'']]],
  ['data_20dao_5froutinglabelhistory_20cs_64',['File: Module_Routing/Data/Dao_RoutingLabelHistory.cs',['../md_repomix-output-code-only.html#autotoc_md490',1,'']]],
  ['data_20dao_5froutingotherreason_20cs_65',['File: Module_Routing/Data/Dao_RoutingOtherReason.cs',['../md_repomix-output-code-only.html#autotoc_md424',1,'']]],
  ['data_20dao_5froutingrecipient_20cs_66',['File: Module_Routing/Data/Dao_RoutingRecipient.cs',['../md_repomix-output-code-only.html#autotoc_md307',1,'']]],
  ['data_20dao_5froutingrule_20cs_67',['File: Module_Settings/Data/Dao_RoutingRule.cs',['../md_repomix-output-code-only.html#autotoc_md476',1,'']]],
  ['data_20dao_5froutingusagetracking_20cs_68',['File: Module_Routing/Data/Dao_RoutingUsageTracking.cs',['../md_repomix-output-code-only.html#autotoc_md425',1,'']]],
  ['data_20dao_5froutinguserpreference_20cs_69',['File: Module_Routing/Data/Dao_RoutingUserPreference.cs',['../md_repomix-output-code-only.html#autotoc_md426',1,'']]],
  ['data_20dao_5fscheduledreport_20cs_70',['File: Module_Settings/Data/Dao_ScheduledReport.cs',['../md_repomix-output-code-only.html#autotoc_md438',1,'']]],
  ['data_20dao_5fsettingsauditlog_20cs_71',['File: Module_Settings/Data/Dao_SettingsAuditLog.cs',['../md_repomix-output-code-only.html#autotoc_md477',1,'']]],
  ['data_20dao_5fsystemsettings_20cs_72',['File: Module_Settings/Data/Dao_SystemSettings.cs',['../md_repomix-output-code-only.html#autotoc_md439',1,'']]],
  ['data_20dao_5fusersettings_20cs_73',['File: Module_Settings/Data/Dao_UserSettings.cs',['../md_repomix-output-code-only.html#autotoc_md440',1,'']]],
  ['data_20dao_5fvolvopart_20cs_74',['File: Module_Volvo/Data/Dao_VolvoPart.cs',['../md_repomix-output-code-only.html#autotoc_md493',1,'']]],
  ['data_20dao_5fvolvopartcomponent_20cs_75',['File: Module_Volvo/Data/Dao_VolvoPartComponent.cs',['../md_repomix-output-code-only.html#autotoc_md478',1,'']]],
  ['data_20dao_5fvolvosettings_20cs_76',['File: Module_Volvo/Data/Dao_VolvoSettings.cs',['../md_repomix-output-code-only.html#autotoc_md494',1,'']]],
  ['data_20dao_5fvolvoshipment_20cs_77',['File: Module_Volvo/Data/Dao_VolvoShipment.cs',['../md_repomix-output-code-only.html#autotoc_md503',1,'']]],
  ['data_20dao_5fvolvoshipmentline_20cs_78',['File: Module_Volvo/Data/Dao_VolvoShipmentLine.cs',['../md_repomix-output-code-only.html#autotoc_md495',1,'']]],
  ['data_20inforvisual_20dao_5finforvisualconnection_20cs_79',['File: Module_Core/Data/InforVisual/Dao_InforVisualConnection.cs',['../md_repomix-output-code-only.html#autotoc_md105',1,'']]],
  ['data_20inforvisual_20dao_5finforvisualpart_20cs_80',['File: Module_Core/Data/InforVisual/Dao_InforVisualPart.cs',['../md_repomix-output-code-only.html#autotoc_md106',1,'']]],
  ['data_20inforvisual_20dao_5finforvisualpo_20cs_81',['File: Module_Core/Data/InforVisual/Dao_InforVisualPO.cs',['../md_repomix-output-code-only.html#autotoc_md107',1,'']]],
  ['database_82',['Database',['../md__a_g_e_n_t_s.html#autotoc_md9',1,'Database'],['../md__a_g_e_n_t_s.html#autotoc_md29',1,'Database']]],
  ['database_20connection_20errors_83',['Database Connection Errors',['../md__r_e_a_d_m_e.html#autotoc_md71',1,'']]],
  ['database_20helper_5fdatabase_5fstoredprocedure_20cs_84',['File: Module_Core/Helpers/Database/Helper_Database_StoredProcedure.cs',['../md_repomix-output-code-only.html#autotoc_md393',1,'']]],
  ['database_20helper_5fdatabase_5fstoredprocedure_5ftests_20cs_85',['File: MTM_Receiving_Application.Tests/Module_Core/Helpers/Database/Helper_Database_StoredProcedure_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md364',1,'']]],
  ['database_20helper_5fdatabase_5fvariables_20cs_86',['File: Module_Core/Helpers/Database/Helper_Database_Variables.cs',['../md_repomix-output-code-only.html#autotoc_md487',1,'']]],
  ['database_20helper_5fdatabase_5fvariables_5ftests_20cs_87',['File: MTM_Receiving_Application.Tests/Module_Core/Helpers/Database/Helper_Database_Variables_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md365',1,'']]],
  ['database_20helper_5fsqlqueryloader_20cs_88',['File: Module_Core/Helpers/Database/Helper_SqlQueryLoader.cs',['../md_repomix-output-code-only.html#autotoc_md108',1,'']]],
  ['database_20operations_89',['MySQL Database Operations',['../md__a_g_e_n_t_s.html#autotoc_md20',1,'']]],
  ['database_20security_90',['Database Security',['../md__r_e_a_d_m_e.html#autotoc_md81',1,'']]],
  ['database_20service_5ferrorhandler_20cs_91',['File: Module_Core/Services/Database/Service_ErrorHandler.cs',['../md_repomix-output-code-only.html#autotoc_md127',1,'']]],
  ['database_20service_5ferrorhandler_5ftests_20cs_92',['File: MTM_Receiving_Application.Tests/Module_Core/Services/Database/Service_ErrorHandler_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md371',1,'']]],
  ['database_20service_5finforvisualconnect_20cs_93',['File: Module_Core/Services/Database/Service_InforVisualConnect.cs',['../md_repomix-output-code-only.html#autotoc_md128',1,'']]],
  ['database_20service_5floggingutility_20cs_94',['File: Module_Core/Services/Database/Service_LoggingUtility.cs',['../md_repomix-output-code-only.html#autotoc_md258',1,'']]],
  ['database_20setup_95',['2. Database Setup',['../md__r_e_a_d_m_e.html#autotoc_md54',1,'']]],
  ['databasefixture_20cs_96',['File: MTM_Receiving_Application.Tests/Fixtures/DatabaseFixture.cs',['../md_repomix-output-code-only.html#autotoc_md348',1,'']]],
  ['defaults_20inforvisualdefaults_20cs_97',['File: Module_Core/Defaults/InforVisualDefaults.cs',['../md_repomix-output-code-only.html#autotoc_md247',1,'']]],
  ['defaults_20inforvisualdefaults_5ftests_20cs_98',['File: MTM_Receiving_Application.Tests/Module_Core/Defaults/InforVisualDefaults_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md362',1,'']]],
  ['defaults_20workstationdefaults_20cs_99',['File: Module_Core/Defaults/WorkstationDefaults.cs',['../md_repomix-output-code-only.html#autotoc_md248',1,'']]],
  ['defaults_20workstationdefaults_5ftests_20cs_100',['File: MTM_Receiving_Application.Tests/Module_Core/Defaults/WorkstationDefaults_Tests.cs',['../md_repomix-output-code-only.html#autotoc_md363',1,'']]],
  ['department_20management_101',['Department Management',['../md__r_e_a_d_m_e.html#autotoc_md59',1,'']]],
  ['dependency_20injection_20registration_102',['Dependency Injection Registration',['../md__a_g_e_n_t_s.html#autotoc_md18',1,'']]],
  ['developers_103',['For Developers',['../md__r_e_a_d_m_e.html#autotoc_md48',1,'']]],
  ['development_104',['Development',['../md__r_e_a_d_m_e.html#autotoc_md72',1,'']]],
  ['development_20guidelines_105',['Development Guidelines',['../md__r_e_a_d_m_e.html#autotoc_md50',1,'']]],
  ['development_20standards_106',['Development Standards',['../md__a_g_e_n_t_s.html#autotoc_md15',1,'']]],
  ['directory_20structure_107',['Directory Structure',['../md_repomix-output-copilot-docs.html#autotoc_md520',1,'']]],
  ['do_108',['Do',['../md__a_g_e_n_t_s.html#autotoc_md23',1,'✅ Always Do'],['../md__a_g_e_n_t_s.html#autotoc_md25',1,'🚫 Never Do']]],
  ['docs_109',['repomix-output-copilot-docs',['../md_repomix-output-copilot-docs.html',1,'']]],
  ['documentation_110',['Documentation',['../md__a_g_e_n_t_s.html#autotoc_md26',1,'Key Files &amp;amp; Documentation'],['../md__a_g_e_n_t_s.html#autotoc_md28',1,'Reference Documentation']]],
  ['documentation_20standards_111',['Documentation Standards',['../md__a_g_e_n_t_s.html#autotoc_md17',1,'']]]
];
