CREATE TABLE IF NOT EXISTS receiving_history (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Auto-incrementing unique identifier',
    load_guid CHAR(36) NULL COMMENT 'GUID identifier for app-generated records; NULL for imported historical records',
    quantity INT NOT NULL COMMENT 'Quantity of parts received on this label/skid',
    weight_quantity DECIMAL(18, 2) NULL DEFAULT NULL COMMENT 'Raw weight or quantity value entered by the operator',
    part_id VARCHAR(50) NOT NULL COMMENT 'Part identifier from Infor Visual',
    part_type VARCHAR(50) NULL DEFAULT NULL COMMENT 'Part type classification (Standard, Coil, etc.)',
    po_number VARCHAR(20) NULL COMMENT 'Purchase order number (VARCHAR to support formats like PO-066914 and PO-064489B)',
    po_line_number VARCHAR(10) NULL COMMENT 'Purchase order line number from Infor Visual',
    employee_number INT NOT NULL DEFAULT 0 COMMENT 'Employee ID who processed the receiving',
    heat VARCHAR(100) COMMENT 'Heat/lot number for material traceability (optional)',
    transaction_date DATE NOT NULL COMMENT 'Date the receiving transaction occurred',
    initial_location VARCHAR(50) COMMENT 'Initial warehouse location for received parts (optional)',
    coils_on_skid INT COMMENT 'Number of coils on the skid (for coil materials, optional)',
    label_number INT DEFAULT 1 COMMENT 'Sequential label number when splitting quantities (default: 1)',
    load_number INT NULL COMMENT 'Sequential load number within the receiving session',
    vendor_name VARCHAR(255) COMMENT 'Vendor/supplier name (optional, for reference)',
    part_description VARCHAR(500) COMMENT 'Part description from Infor Visual (optional, for reference)',
    po_status VARCHAR(100) NULL COMMENT 'PO status snapshot',
    po_due_date DATE NULL COMMENT 'PO due date snapshot selected for receiving history',
    qty_ordered DECIMAL(18, 2) NULL COMMENT 'Ordered quantity snapshot',
    unit_of_measure VARCHAR(20) NULL COMMENT 'Unit of measure snapshot',
    remaining_quantity INT NULL COMMENT 'Remaining PO quantity snapshot',
    user_id VARCHAR(100) NULL COMMENT 'Windows user / app user id snapshot',
    user_set_customer_name VARCHAR(255) NULL COMMENT 'Matched vendor/customer name that enables the user-set variable field',
    user_set_variable VARCHAR(255) NULL COMMENT 'User-entered variable value captured for the matched vendor/customer',
    packages_per_load INT NULL COMMENT 'Number of packages per load/skid',
    package_type_name VARCHAR(50) NULL COMMENT 'Package type description (Skid, Box, Coil, etc.)',
    weight_per_package DECIMAL(18, 2) NULL COMMENT 'Weight of each individual package',
    is_non_po_item TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Non-PO item flag: 1 when part not found in Infor Visual and no PO number',
    is_quality_hold_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 when the part requires a quality hold acknowledgment',
    is_quality_hold_acknowledged TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 when quality hold has been formally acknowledged',
    is_reprint TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 when this row was re-queued from receiving_history for a label reprint',
    quality_hold_restriction_type VARCHAR(255) NULL COMMENT 'Restriction type code from the quality hold check',
    part_skid_sequence INT NULL COMMENT 'Position of this skid among all skids for the same part in the saved batch',
    part_skid_total INT NULL COMMENT 'Total skids for the same part in the saved batch',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp when record was created',
    UNIQUE INDEX idx_load_guid (load_guid) COMMENT 'Unique index for app GUID lookups (allows NULLs for imported records)',
    INDEX idx_part_id (part_id) COMMENT 'Index for part lookup queries',
    INDEX idx_po_number (po_number) COMMENT 'Index for PO-based queries',
    INDEX idx_po_line_number (po_line_number) COMMENT 'Index for PO line lookups',
    INDEX idx_po_due_date (po_due_date) COMMENT 'Index for PO due-date queries',
    INDEX idx_transaction_date (transaction_date) COMMENT 'Index for date range queries',
    INDEX idx_employee_number (employee_number) COMMENT 'Index for employee activity queries',
    INDEX idx_user_id (user_id) COMMENT 'Index for user-based history queries'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Receiving history - stores all receiving transactions matching receiving_label_data structure';