CREATE TABLE IF NOT EXISTS dunnage_label_data (
    id INT AUTO_INCREMENT PRIMARY KEY COMMENT 'Auto-incrementing unique identifier',
    load_uuid CHAR(36) NOT NULL COMMENT 'GUID identifying the load transaction from the workflow session',
    part_id VARCHAR(50) NOT NULL COMMENT 'Part identifier from dunnage_parts',
    dunnage_type_id INT NULL COMMENT 'FK to dunnage_types.id; snapshot at time of save',
    dunnage_type_name VARCHAR(100) NULL COMMENT 'Type name snapshot (e.g. Corrugated Cardboard)',
    dunnage_type_icon VARCHAR(100) NULL COMMENT 'MaterialIconKind string snapshot (e.g. PackageVariantClosed)',
    quantity DECIMAL(10, 2) NOT NULL COMMENT 'Quantity received in this transaction',
    quantity_type VARCHAR(100) NOT NULL DEFAULT 'Quantity' COMMENT 'Quantity label header snapshot copied from dunnage_parts at save time',
    po_number VARCHAR(50) NULL COMMENT 'PO number; NULL for non-PO items',
    received_date DATETIME NOT NULL COMMENT 'Date and time the dunnage was received',
    user_id VARCHAR(100) NOT NULL COMMENT 'Application user identifier (Windows username)',
    employee_number INT NULL COMMENT '4-digit employee identifier for the user who saved the queue row',
    location VARCHAR(100) NULL COMMENT 'Warehouse location for received dunnage',
    label_number VARCHAR(50) NULL COMMENT 'Label number for this row (supports multi-label splits)',
    part_skid_sequence INT NULL COMMENT 'Position of this skid among all skids for the same part in the saved batch',
    part_skid_total INT NULL COMMENT 'Total skids for the same part in the saved batch',
    udc1 VARCHAR(255) NULL COMMENT 'User Defined Column slot 1 snapshot - display name from dunnage_custom_fields',
    udc2 VARCHAR(255) NULL COMMENT 'User Defined Column slot 2 snapshot - display name from dunnage_custom_fields',
    udc3 VARCHAR(255) NULL COMMENT 'User Defined Column slot 3 snapshot - display name from dunnage_custom_fields',
    udc4 VARCHAR(255) NULL COMMENT 'User Defined Column slot 4 snapshot - display name from dunnage_custom_fields',
    udc5 VARCHAR(255) NULL COMMENT 'User Defined Column slot 5 snapshot - display name from dunnage_custom_fields',
    udc6 VARCHAR(255) NULL COMMENT 'User Defined Column slot 6 snapshot - display name from dunnage_custom_fields',
    udc7 VARCHAR(255) NULL COMMENT 'User Defined Column slot 7 snapshot - display name from dunnage_custom_fields',
    udc8 VARCHAR(255) NULL COMMENT 'User Defined Column slot 8 snapshot - display name from dunnage_custom_fields',
    udc9 VARCHAR(255) NULL COMMENT 'User Defined Column slot 9 snapshot - display name from dunnage_custom_fields',
    udc10 VARCHAR(255) NULL COMMENT 'User Defined Column slot 10 snapshot - display name from dunnage_custom_fields',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Timestamp when the queue record was inserted',
    INDEX idx_load_uuid (load_uuid) COMMENT 'Lookup by workflow session GUID',
    INDEX idx_part_id (part_id) COMMENT 'Part-based queue queries',
    INDEX idx_employee_number (employee_number) COMMENT 'User-scoped clear queue filtering',
    INDEX idx_received_date (received_date) COMMENT 'Date range filtering for queue consumers'
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Active dunnage label queue. Rows are moved to dunnage_history on Clear Label Data. Do not write directly to dunnage_history from the workflow.';