/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "My Project", "index.html", [
    [ "MTM Receiving Application - Custom Agent", "md__a_g_e_n_t_s.html", [
      [ "Your Role", "md__a_g_e_n_t_s.html#autotoc_md1", null ],
      [ "Project Knowledge", "md__a_g_e_n_t_s.html#autotoc_md2", [
        [ "Tech Stack", "md__a_g_e_n_t_s.html#autotoc_md3", null ],
        [ "File Structure", "md__a_g_e_n_t_s.html#autotoc_md4", null ],
        [ "Critical Constraints", "md__a_g_e_n_t_s.html#autotoc_md5", null ]
      ] ],
      [ "MCP Tools (Preferred in this workspace)", "md__a_g_e_n_t_s.html#autotoc_md6", null ],
      [ "Commands You Can Use", "md__a_g_e_n_t_s.html#autotoc_md7", [
        [ "Build &amp; Test", "md__a_g_e_n_t_s.html#autotoc_md8", null ],
        [ "Database", "md__a_g_e_n_t_s.html#autotoc_md9", null ],
        [ "XAML Troubleshooting", "md__a_g_e_n_t_s.html#autotoc_md10", null ]
      ] ],
      [ "Architecture Patterns", "md__a_g_e_n_t_s.html#autotoc_md11", [
        [ "ViewModel Pattern (Mandatory)", "md__a_g_e_n_t_s.html#autotoc_md12", null ],
        [ "DAO Pattern (Mandatory)", "md__a_g_e_n_t_s.html#autotoc_md13", null ],
        [ "View Pattern (Mandatory)", "md__a_g_e_n_t_s.html#autotoc_md14", null ]
      ] ],
      [ "Development Standards", "md__a_g_e_n_t_s.html#autotoc_md15", [
        [ "Naming Conventions", "md__a_g_e_n_t_s.html#autotoc_md16", null ],
        [ "Documentation Standards", "md__a_g_e_n_t_s.html#autotoc_md17", null ],
        [ "Dependency Injection Registration", "md__a_g_e_n_t_s.html#autotoc_md18", null ],
        [ "Error Handling", "md__a_g_e_n_t_s.html#autotoc_md19", null ],
        [ "MySQL Database Operations", "md__a_g_e_n_t_s.html#autotoc_md20", null ],
        [ "Infor Visual (SQL Server) Operations - READ ONLY", "md__a_g_e_n_t_s.html#autotoc_md21", null ]
      ] ],
      [ "Boundaries", "md__a_g_e_n_t_s.html#autotoc_md22", [
        [ "✅ Always Do", "md__a_g_e_n_t_s.html#autotoc_md23", null ],
        [ "⚠️ Ask First", "md__a_g_e_n_t_s.html#autotoc_md24", null ],
        [ "🚫 Never Do", "md__a_g_e_n_t_s.html#autotoc_md25", null ]
      ] ],
      [ "Key Files &amp; Documentation", "md__a_g_e_n_t_s.html#autotoc_md26", [
        [ "Essential Reading", "md__a_g_e_n_t_s.html#autotoc_md27", null ],
        [ "Reference Documentation", "md__a_g_e_n_t_s.html#autotoc_md28", null ],
        [ "Database", "md__a_g_e_n_t_s.html#autotoc_md29", null ]
      ] ],
      [ "Workflow Example: Adding a New Feature", "md__a_g_e_n_t_s.html#autotoc_md30", null ],
      [ "Common Pitfalls to Avoid", "md__a_g_e_n_t_s.html#autotoc_md31", null ],
      [ "Quick Reference Commands", "md__a_g_e_n_t_s.html#autotoc_md32", null ]
    ] ],
    [ "MTM Receiving Application", "md__r_e_a_d_m_e.html", [
      [ "Overview", "md__r_e_a_d_m_e.html#autotoc_md35", null ],
      [ "Copilot MCP (High-Intelligence Setup)", "md__r_e_a_d_m_e.html#autotoc_md36", null ],
      [ "Features", "md__r_e_a_d_m_e.html#autotoc_md37", [
        [ "Authentication System", "md__r_e_a_d_m_e.html#autotoc_md38", [
          [ "Personal Workstation (Auto-Login)", "md__r_e_a_d_m_e.html#autotoc_md39", null ],
          [ "Shared Terminal (PIN Login)", "md__r_e_a_d_m_e.html#autotoc_md40", null ],
          [ "New User Creation", "md__r_e_a_d_m_e.html#autotoc_md41", null ]
        ] ],
        [ "Session Management", "md__r_e_a_d_m_e.html#autotoc_md42", null ],
        [ "Receiving Workflow", "md__r_e_a_d_m_e.html#autotoc_md43", null ],
        [ "Label Generation", "md__r_e_a_d_m_e.html#autotoc_md44", null ],
        [ "Help System", "md__r_e_a_d_m_e.html#autotoc_md45", [
          [ "Features", "md__r_e_a_d_m_e.html#autotoc_md46", null ],
          [ "Using the Help System", "md__r_e_a_d_m_e.html#autotoc_md47", null ],
          [ "For Developers", "md__r_e_a_d_m_e.html#autotoc_md48", null ]
        ] ]
      ] ],
      [ "Technology Stack", "md__r_e_a_d_m_e.html#autotoc_md49", null ],
      [ "Development Guidelines", "md__r_e_a_d_m_e.html#autotoc_md50", null ],
      [ "Prerequisites", "md__r_e_a_d_m_e.html#autotoc_md51", null ],
      [ "Installation", "md__r_e_a_d_m_e.html#autotoc_md52", [
        [ "1. Clone Repository", "md__r_e_a_d_m_e.html#autotoc_md53", null ],
        [ "2. Database Setup", "md__r_e_a_d_m_e.html#autotoc_md54", null ],
        [ "3. Configure Connection String", "md__r_e_a_d_m_e.html#autotoc_md55", null ],
        [ "4. Build and Run", "md__r_e_a_d_m_e.html#autotoc_md56", null ]
      ] ],
      [ "Configuration", "md__r_e_a_d_m_e.html#autotoc_md57", [
        [ "Workstation Setup", "md__r_e_a_d_m_e.html#autotoc_md58", null ],
        [ "Department Management", "md__r_e_a_d_m_e.html#autotoc_md59", null ]
      ] ],
      [ "Project Structure", "md__r_e_a_d_m_e.html#autotoc_md60", null ],
      [ "Usage", "md__r_e_a_d_m_e.html#autotoc_md61", [
        [ "First Launch", "md__r_e_a_d_m_e.html#autotoc_md62", null ],
        [ "Session Management", "md__r_e_a_d_m_e.html#autotoc_md63", null ],
        [ "Creating New Users", "md__r_e_a_d_m_e.html#autotoc_md64", null ]
      ] ],
      [ "Testing", "md__r_e_a_d_m_e.html#autotoc_md65", [
        [ "Manual Tests", "md__r_e_a_d_m_e.html#autotoc_md66", null ],
        [ "Runtime Testing", "md__r_e_a_d_m_e.html#autotoc_md67", null ]
      ] ],
      [ "Troubleshooting", "md__r_e_a_d_m_e.html#autotoc_md68", [
        [ "Application Won't Start", "md__r_e_a_d_m_e.html#autotoc_md69", null ],
        [ "Authentication Fails", "md__r_e_a_d_m_e.html#autotoc_md70", null ],
        [ "Database Connection Errors", "md__r_e_a_d_m_e.html#autotoc_md71", null ]
      ] ],
      [ "Development", "md__r_e_a_d_m_e.html#autotoc_md72", [
        [ "Building from Source", "md__r_e_a_d_m_e.html#autotoc_md73", null ],
        [ "Code Style", "md__r_e_a_d_m_e.html#autotoc_md74", null ],
        [ "Adding New Features", "md__r_e_a_d_m_e.html#autotoc_md75", null ]
      ] ],
      [ "Contributing", "md__r_e_a_d_m_e.html#autotoc_md76", [
        [ "Branch Structure", "md__r_e_a_d_m_e.html#autotoc_md77", null ],
        [ "Pull Request Process", "md__r_e_a_d_m_e.html#autotoc_md78", null ]
      ] ],
      [ "Security", "md__r_e_a_d_m_e.html#autotoc_md79", [
        [ "Authentication Security", "md__r_e_a_d_m_e.html#autotoc_md80", null ],
        [ "Database Security", "md__r_e_a_d_m_e.html#autotoc_md81", null ],
        [ "ERP Credentials", "md__r_e_a_d_m_e.html#autotoc_md82", null ]
      ] ],
      [ "License", "md__r_e_a_d_m_e.html#autotoc_md83", null ],
      [ "Support", "md__r_e_a_d_m_e.html#autotoc_md84", null ],
      [ "Acknowledgments", "md__r_e_a_d_m_e.html#autotoc_md85", null ]
    ] ],
    [ "User Provided Header", "md_repomix-output-code-only.html", [
      [ "Files", "md_repomix-output-code-only.html#autotoc_md88", [
        [ "File: App.xaml", "md_repomix-output-code-only.html#autotoc_md89", null ],
        [ "File: Module_Core/Contracts/Services/IService_CSVWriter.cs", "md_repomix-output-code-only.html#autotoc_md90", null ],
        [ "File: Module_Core/Contracts/Services/IService_Dispatcher.cs", "md_repomix-output-code-only.html#autotoc_md91", null ],
        [ "File: Module_Core/Contracts/Services/IService_ErrorHandler.cs", "md_repomix-output-code-only.html#autotoc_md92", null ],
        [ "File: Module_Core/Contracts/Services/IService_Help.cs", "md_repomix-output-code-only.html#autotoc_md93", null ],
        [ "File: Module_Core/Contracts/Services/IService_InforVisual.cs", "md_repomix-output-code-only.html#autotoc_md94", null ],
        [ "File: Module_Core/Contracts/Services/IService_LoggingUtility.cs", "md_repomix-output-code-only.html#autotoc_md95", null ],
        [ "File: Module_Core/Contracts/Services/IService_Notification.cs", "md_repomix-output-code-only.html#autotoc_md96", null ],
        [ "File: Module_Core/Contracts/Services/IService_OnStartup_AppLifecycle.cs", "md_repomix-output-code-only.html#autotoc_md97", null ],
        [ "File: Module_Core/Contracts/Services/IService_Pagination.cs", "md_repomix-output-code-only.html#autotoc_md98", null ],
        [ "File: Module_Core/Contracts/Services/IService_SessionManager.cs", "md_repomix-output-code-only.html#autotoc_md99", null ],
        [ "File: Module_Core/Contracts/Services/IService_UserSessionManager.cs", "md_repomix-output-code-only.html#autotoc_md100", null ],
        [ "File: Module_Core/Contracts/Services/IService_ViewModelRegistry.cs", "md_repomix-output-code-only.html#autotoc_md101", null ],
        [ "File: Module_Core/Contracts/Services/ITimer.cs", "md_repomix-output-code-only.html#autotoc_md102", null ],
        [ "File: Module_Core/Contracts/Services/IWindowService.cs", "md_repomix-output-code-only.html#autotoc_md103", null ],
        [ "File: Module_Core/Contracts/Services/Navigation/IService_Navigation.cs", "md_repomix-output-code-only.html#autotoc_md104", null ],
        [ "File: Module_Core/Data/InforVisual/Dao_InforVisualConnection.cs", "md_repomix-output-code-only.html#autotoc_md105", null ],
        [ "File: Module_Core/Data/InforVisual/Dao_InforVisualPart.cs", "md_repomix-output-code-only.html#autotoc_md106", null ],
        [ "File: Module_Core/Data/InforVisual/Dao_InforVisualPO.cs", "md_repomix-output-code-only.html#autotoc_md107", null ],
        [ "File: Module_Core/Helpers/Database/Helper_SqlQueryLoader.cs", "md_repomix-output-code-only.html#autotoc_md108", null ],
        [ "File: Module_Core/Helpers/UI/Helper_MaterialIcons.cs", "md_repomix-output-code-only.html#autotoc_md109", null ],
        [ "File: Module_Core/Helpers/UI/Helper_WindowExtensions.cs", "md_repomix-output-code-only.html#autotoc_md110", null ],
        [ "File: Module_Core/Helpers/UI/Helper_WorkflowHelpContentGenerator.cs", "md_repomix-output-code-only.html#autotoc_md111", null ],
        [ "File: Module_Core/Models/Core/Model_Dao_Result_Generic.cs", "md_repomix-output-code-only.html#autotoc_md112", null ],
        [ "File: Module_Core/Models/Core/Model_Dao_Result.cs", "md_repomix-output-code-only.html#autotoc_md113", null ],
        [ "File: Module_Core/Models/Core/Model_HelpContent.cs", "md_repomix-output-code-only.html#autotoc_md114", null ],
        [ "File: Module_Core/Models/Enums/Enum_DataSourceType.cs", "md_repomix-output-code-only.html#autotoc_md115", null ],
        [ "File: Module_Core/Models/Enums/Enum_ErrorSeverity.cs", "md_repomix-output-code-only.html#autotoc_md116", null ],
        [ "File: Module_Core/Models/Enums/Enum_HelpSeverity.cs", "md_repomix-output-code-only.html#autotoc_md117", null ],
        [ "File: Module_Core/Models/Enums/Enum_HelpType.cs", "md_repomix-output-code-only.html#autotoc_md118", null ],
        [ "File: Module_Core/Models/Enums/Enum_InfoBarSeverity.cs", "md_repomix-output-code-only.html#autotoc_md119", null ],
        [ "File: Module_Core/Models/Enums/Enum_LabelType.cs", "md_repomix-output-code-only.html#autotoc_md120", null ],
        [ "File: Module_Core/Models/Enums/Enum_PackageType.cs", "md_repomix-output-code-only.html#autotoc_md121", null ],
        [ "File: Module_Core/Models/Enums/Enum_ReceivingWorkflowStep.cs", "md_repomix-output-code-only.html#autotoc_md122", null ],
        [ "File: Module_Core/Models/Enums/Enum_ValidationSeverity.cs", "md_repomix-output-code-only.html#autotoc_md123", null ],
        [ "File: Module_Core/Models/Systems/Model_AppSettings.cs", "md_repomix-output-code-only.html#autotoc_md124", null ],
        [ "File: Module_Core/Models/Systems/Model_CreateUserResult.cs", "md_repomix-output-code-only.html#autotoc_md125", null ],
        [ "File: Module_Core/Models/Systems/Model_SessionTimedOutEventArgs.cs", "md_repomix-output-code-only.html#autotoc_md126", null ],
        [ "File: Module_Core/Services/Database/Service_ErrorHandler.cs", "md_repomix-output-code-only.html#autotoc_md127", null ],
        [ "File: Module_Core/Services/Database/Service_InforVisualConnect.cs", "md_repomix-output-code-only.html#autotoc_md128", null ],
        [ "File: Module_Core/Services/Help/Service_Help.cs", "md_repomix-output-code-only.html#autotoc_md129", null ],
        [ "File: Module_Core/Services/Navigation/Service_Navigation.cs", "md_repomix-output-code-only.html#autotoc_md130", null ],
        [ "File: Module_Core/Services/Service_Dispatcher.cs", "md_repomix-output-code-only.html#autotoc_md131", null ],
        [ "File: Module_Core/Services/Service_DispatcherTimerWrapper.cs", "md_repomix-output-code-only.html#autotoc_md132", null ],
        [ "File: Module_Core/Services/Service_Notification.cs", "md_repomix-output-code-only.html#autotoc_md133", null ],
        [ "File: Module_Core/Services/Service_Pagination.cs", "md_repomix-output-code-only.html#autotoc_md134", null ],
        [ "File: Module_Core/Services/Service_Window.cs", "md_repomix-output-code-only.html#autotoc_md135", null ],
        [ "File: Module_Core/Services/UI/Service_ViewModelRegistry.cs", "md_repomix-output-code-only.html#autotoc_md136", null ],
        [ "File: Module_Core/Themes/MaterialIcons.xaml", "md_repomix-output-code-only.html#autotoc_md137", null ],
        [ "File: Module_Dunnage/Enums/Enum_DunnageWorkflowStep.cs", "md_repomix-output-code-only.html#autotoc_md138", null ],
        [ "File: Module_Dunnage/Models/Model_DunnageLine.cs", "md_repomix-output-code-only.html#autotoc_md139", null ],
        [ "File: Module_Dunnage/Models/Model_DunnagePart.cs", "md_repomix-output-code-only.html#autotoc_md140", null ],
        [ "File: Module_Dunnage/Models/Model_DunnageSession.cs", "md_repomix-output-code-only.html#autotoc_md141", null ],
        [ "File: Module_Dunnage/Models/Model_DunnageSpec.cs", "md_repomix-output-code-only.html#autotoc_md142", null ],
        [ "File: Module_Dunnage/Models/Model_DunnageType.cs", "md_repomix-output-code-only.html#autotoc_md143", null ],
        [ "File: Module_Dunnage/Models/Model_IconDefinition.cs", "md_repomix-output-code-only.html#autotoc_md144", null ],
        [ "File: Module_Dunnage/Models/Model_InventoriedDunnage.cs", "md_repomix-output-code-only.html#autotoc_md145", null ],
        [ "File: Module_Dunnage/Models/Model_SpecInput.cs", "md_repomix-output-code-only.html#autotoc_md146", null ],
        [ "File: Module_Dunnage/Models/Model_SpecItem.cs", "md_repomix-output-code-only.html#autotoc_md147", null ],
        [ "File: Module_Dunnage/Models/SpecDefinition.cs", "md_repomix-output-code-only.html#autotoc_md148", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminInventoryView.xaml", "md_repomix-output-code-only.html#autotoc_md149", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminMainView.xaml", "md_repomix-output-code-only.html#autotoc_md150", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminMainView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md151", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminPartsView.xaml", "md_repomix-output-code-only.html#autotoc_md152", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminPartsView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md153", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminTypesView.xaml", "md_repomix-output-code-only.html#autotoc_md154", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Control_IconPickerControl.xaml", "md_repomix-output-code-only.html#autotoc_md155", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_DetailsEntryView.xaml", "md_repomix-output-code-only.html#autotoc_md156", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_DetailsEntryView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md157", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_AddMultipleRowsDialog.xaml", "md_repomix-output-code-only.html#autotoc_md158", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_AddMultipleRowsDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md159", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_AddToInventoriedListDialog.xaml", "md_repomix-output-code-only.html#autotoc_md160", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_AddToInventoriedListDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md161", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_Dunnage_AddTypeDialog.xaml", "md_repomix-output-code-only.html#autotoc_md162", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Dialog_Dunnage_AddTypeDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md163", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_EditModeView.xaml", "md_repomix-output-code-only.html#autotoc_md164", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_EditModeView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md165", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ManualEntryView.xaml", "md_repomix-output-code-only.html#autotoc_md166", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ManualEntryView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md167", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ModeSelectionView.xaml", "md_repomix-output-code-only.html#autotoc_md168", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ModeSelectionView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md169", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_PartSelectionView.xaml", "md_repomix-output-code-only.html#autotoc_md170", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_PartSelectionView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md171", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuantityEntryView.xaml", "md_repomix-output-code-only.html#autotoc_md172", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuantityEntryView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md173", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuickAddPartDialog.xaml", "md_repomix-output-code-only.html#autotoc_md174", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuickAddTypeDialog.xaml", "md_repomix-output-code-only.html#autotoc_md175", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuickAddTypeDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md176", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ReviewView.xaml", "md_repomix-output-code-only.html#autotoc_md177", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_ReviewView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md178", null ],
        [ "File: Module_Receiving/Models/Model_Application_Variables.cs", "md_repomix-output-code-only.html#autotoc_md179", null ],
        [ "File: Module_Receiving/Models/Model_CSVDeleteResult.cs", "md_repomix-output-code-only.html#autotoc_md180", null ],
        [ "File: Module_Receiving/Models/Model_CSVExistenceResult.cs", "md_repomix-output-code-only.html#autotoc_md181", null ],
        [ "File: Module_Receiving/Models/Model_CSVWriteResult.cs", "md_repomix-output-code-only.html#autotoc_md182", null ],
        [ "File: Module_Receiving/Models/Model_InforVisualPart.cs", "md_repomix-output-code-only.html#autotoc_md183", null ],
        [ "File: Module_Receiving/Models/Model_InforVisualPO.cs", "md_repomix-output-code-only.html#autotoc_md184", null ],
        [ "File: Module_Receiving/Models/Model_PackageTypePreference.cs", "md_repomix-output-code-only.html#autotoc_md185", null ],
        [ "File: Module_Receiving/Models/Model_SaveResult.cs", "md_repomix-output-code-only.html#autotoc_md186", null ],
        [ "File: Module_Receiving/Models/Model_UserPreference.cs", "md_repomix-output-code-only.html#autotoc_md187", null ],
        [ "File: Module_Receiving/Models/Model_WorkflowStepResult.cs", "md_repomix-output-code-only.html#autotoc_md188", null ],
        [ "File: Module_Receiving/Views/View_Receiving_EditMode.xaml", "md_repomix-output-code-only.html#autotoc_md189", null ],
        [ "File: Module_Receiving/Views/View_Receiving_EditMode.xaml.cs", "md_repomix-output-code-only.html#autotoc_md190", null ],
        [ "File: Module_Receiving/Views/View_Receiving_HeatLot.xaml", "md_repomix-output-code-only.html#autotoc_md191", null ],
        [ "File: Module_Receiving/Views/View_Receiving_HeatLot.xaml.cs", "md_repomix-output-code-only.html#autotoc_md192", null ],
        [ "File: Module_Receiving/Views/View_Receiving_LoadEntry.xaml", "md_repomix-output-code-only.html#autotoc_md193", null ],
        [ "File: Module_Receiving/Views/View_Receiving_LoadEntry.xaml.cs", "md_repomix-output-code-only.html#autotoc_md194", null ],
        [ "File: Module_Receiving/Views/View_Receiving_ManualEntry.xaml", "md_repomix-output-code-only.html#autotoc_md195", null ],
        [ "File: Module_Receiving/Views/View_Receiving_ModeSelection.xaml", "md_repomix-output-code-only.html#autotoc_md196", null ],
        [ "File: Module_Receiving/Views/View_Receiving_ModeSelection.xaml.cs", "md_repomix-output-code-only.html#autotoc_md197", null ],
        [ "File: Module_Receiving/Views/View_Receiving_PackageType.xaml", "md_repomix-output-code-only.html#autotoc_md198", null ],
        [ "File: Module_Receiving/Views/View_Receiving_PackageType.xaml.cs", "md_repomix-output-code-only.html#autotoc_md199", null ],
        [ "File: Module_Receiving/Views/View_Receiving_POEntry.xaml", "md_repomix-output-code-only.html#autotoc_md200", null ],
        [ "File: Module_Receiving/Views/View_Receiving_POEntry.xaml.cs", "md_repomix-output-code-only.html#autotoc_md201", null ],
        [ "File: Module_Receiving/Views/View_Receiving_Review.xaml", "md_repomix-output-code-only.html#autotoc_md202", null ],
        [ "File: Module_Receiving/Views/View_Receiving_Review.xaml.cs", "md_repomix-output-code-only.html#autotoc_md203", null ],
        [ "File: Module_Receiving/Views/View_Receiving_WeightQuantity.xaml", "md_repomix-output-code-only.html#autotoc_md204", null ],
        [ "File: Module_Receiving/Views/View_Receiving_WeightQuantity.xaml.cs", "md_repomix-output-code-only.html#autotoc_md205", null ],
        [ "File: Module_Receiving/Views/View_Receiving_Workflow.xaml", "md_repomix-output-code-only.html#autotoc_md206", null ],
        [ "File: Module_Reporting/Views/View_Reporting_Main.xaml", "md_repomix-output-code-only.html#autotoc_md207", null ],
        [ "File: Module_Reporting/Views/View_Reporting_Main.xaml.cs", "md_repomix-output-code-only.html#autotoc_md208", null ],
        [ "File: Module_Routing/Enums/Enum_RoutingMode.cs", "md_repomix-output-code-only.html#autotoc_md209", null ],
        [ "File: Module_Routing/Views/RoutingWizardContainerView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md210", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep1View.xaml.cs", "md_repomix-output-code-only.html#autotoc_md211", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep3View.xaml.cs", "md_repomix-output-code-only.html#autotoc_md212", null ],
        [ "File: Module_Settings/Enums/Enum_SettingsWorkflowStep.cs", "md_repomix-output-code-only.html#autotoc_md213", null ],
        [ "File: Module_Settings/Interfaces/IService_UserPreferences.cs", "md_repomix-output-code-only.html#autotoc_md214", null ],
        [ "File: Module_Settings/Services/Service_SettingsWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md215", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_Base.cs", "md_repomix-output-code-only.html#autotoc_md216", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_HelpDialog.cs", "md_repomix-output-code-only.html#autotoc_md217", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_NewUserSetup.cs", "md_repomix-output-code-only.html#autotoc_md218", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_SharedTerminalLogin.cs", "md_repomix-output-code-only.html#autotoc_md219", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_SplashScreen.cs", "md_repomix-output-code-only.html#autotoc_md220", null ],
        [ "File: Module_Shared/Views/View_Shared_HelpDialog.xaml", "md_repomix-output-code-only.html#autotoc_md221", null ],
        [ "File: Module_Shared/Views/View_Shared_HelpDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md222", null ],
        [ "File: Module_Shared/Views/View_Shared_IconSelectorWindow.xaml", "md_repomix-output-code-only.html#autotoc_md223", null ],
        [ "File: Module_Shared/Views/View_Shared_IconSelectorWindow.xaml.cs", "md_repomix-output-code-only.html#autotoc_md224", null ],
        [ "File: Module_Shared/Views/View_Shared_NewUserSetupDialog.xaml", "md_repomix-output-code-only.html#autotoc_md225", null ],
        [ "File: Module_Shared/Views/View_Shared_NewUserSetupDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md226", null ],
        [ "File: Module_Shared/Views/View_Shared_SharedTerminalLoginDialog.xaml", "md_repomix-output-code-only.html#autotoc_md227", null ],
        [ "File: Module_Shared/Views/View_Shared_SharedTerminalLoginDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md228", null ],
        [ "File: Module_Shared/Views/View_Shared_SplashScreenWindow.xaml", "md_repomix-output-code-only.html#autotoc_md229", null ],
        [ "File: Module_Shared/Views/View_Shared_SplashScreenWindow.xaml.cs", "md_repomix-output-code-only.html#autotoc_md230", null ],
        [ "File: Module_Volvo/Views/View_Volvo_History.xaml.cs", "md_repomix-output-code-only.html#autotoc_md231", null ],
        [ "File: Module_Volvo/Views/View_Volvo_Settings.xaml.cs", "md_repomix-output-code-only.html#autotoc_md232", null ],
        [ "File: Module_Core/Behaviors/AuditBehavior.cs", "md_repomix-output-code-only.html#autotoc_md233", null ],
        [ "File: Module_Core/Behaviors/LoggingBehavior.cs", "md_repomix-output-code-only.html#autotoc_md234", null ],
        [ "File: Module_Core/Behaviors/ValidationBehavior.cs", "md_repomix-output-code-only.html#autotoc_md235", null ],
        [ "File: Module_Core/Contracts/Services/IService_Focus.cs", "md_repomix-output-code-only.html#autotoc_md236", null ],
        [ "File: Module_Core/Contracts/ViewModels/IResettableViewModel.cs", "md_repomix-output-code-only.html#autotoc_md237", null ],
        [ "File: Module_Core/Converters/Converter_BooleanToVisibility.cs", "md_repomix-output-code-only.html#autotoc_md238", null ],
        [ "File: Module_Core/Converters/Converter_BoolToString.cs", "md_repomix-output-code-only.html#autotoc_md239", null ],
        [ "File: Module_Core/Converters/Converter_DecimalToInt.cs", "md_repomix-output-code-only.html#autotoc_md240", null ],
        [ "File: Module_Core/Converters/Converter_DecimalToString.cs", "md_repomix-output-code-only.html#autotoc_md241", null ],
        [ "File: Module_Core/Converters/Converter_DoubleToDecimal.cs", "md_repomix-output-code-only.html#autotoc_md242", null ],
        [ "File: Module_Core/Converters/Converter_EmptyStringToVisibility.cs", "md_repomix-output-code-only.html#autotoc_md243", null ],
        [ "File: Module_Core/Converters/Converter_IconCodeToGlyph.cs", "md_repomix-output-code-only.html#autotoc_md244", null ],
        [ "File: Module_Core/Converters/Converter_LoadNumberToOneBased.cs", "md_repomix-output-code-only.html#autotoc_md245", null ],
        [ "File: Module_Core/Converters/Converter_StringFormat.cs", "md_repomix-output-code-only.html#autotoc_md246", null ],
        [ "File: Module_Core/Defaults/InforVisualDefaults.cs", "md_repomix-output-code-only.html#autotoc_md247", null ],
        [ "File: Module_Core/Defaults/WorkstationDefaults.cs", "md_repomix-output-code-only.html#autotoc_md248", null ],
        [ "File: Module_Core/Models/Core/Model_Dao_Result_Factory.cs", "md_repomix-output-code-only.html#autotoc_md249", null ],
        [ "File: Module_Core/Models/InforVisual/Model_InforVisualConnection.cs", "md_repomix-output-code-only.html#autotoc_md250", null ],
        [ "File: Module_Core/Models/InforVisual/Model_InforVisualPart.cs", "md_repomix-output-code-only.html#autotoc_md251", null ],
        [ "File: Module_Core/Models/InforVisual/Model_InforVisualPO.cs", "md_repomix-output-code-only.html#autotoc_md252", null ],
        [ "File: Module_Core/Models/Reporting/Model_ReportRow.cs", "md_repomix-output-code-only.html#autotoc_md253", null ],
        [ "File: Module_Core/Models/Systems/Model_AuthenticationResult.cs", "md_repomix-output-code-only.html#autotoc_md254", null ],
        [ "File: Module_Core/Models/Systems/Model_UserSession.cs", "md_repomix-output-code-only.html#autotoc_md255", null ],
        [ "File: Module_Core/Models/Systems/Model_ValidationResult.cs", "md_repomix-output-code-only.html#autotoc_md256", null ],
        [ "File: Module_Core/Services/Authentication/Service_UserSessionManager.cs", "md_repomix-output-code-only.html#autotoc_md257", null ],
        [ "File: Module_Core/Services/Database/Service_LoggingUtility.cs", "md_repomix-output-code-only.html#autotoc_md258", null ],
        [ "File: Module_Core/Services/Service_Focus.cs", "md_repomix-output-code-only.html#autotoc_md259", null ],
        [ "File: Module_Dunnage/Contracts/IService_DunnageAdminWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md260", null ],
        [ "File: Module_Dunnage/Contracts/IService_DunnageCSVWriter.cs", "md_repomix-output-code-only.html#autotoc_md261", null ],
        [ "File: Module_Dunnage/Contracts/IService_DunnageWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md262", null ],
        [ "File: Module_Dunnage/Contracts/IService_MySQL_Dunnage.cs", "md_repomix-output-code-only.html#autotoc_md263", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageLine.cs", "md_repomix-output-code-only.html#autotoc_md264", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnagePart.cs", "md_repomix-output-code-only.html#autotoc_md265", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageSpec.cs", "md_repomix-output-code-only.html#autotoc_md266", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageUserPreference.cs", "md_repomix-output-code-only.html#autotoc_md267", null ],
        [ "File: Module_Dunnage/Enums/Enum_DunnageAdminSection.cs", "md_repomix-output-code-only.html#autotoc_md268", null ],
        [ "File: Module_Dunnage/Models/Model_CustomFieldDefinition.cs", "md_repomix-output-code-only.html#autotoc_md269", null ],
        [ "File: Module_Dunnage/Models/Model_DunnageLoad.cs", "md_repomix-output-code-only.html#autotoc_md270", null ],
        [ "File: Module_Dunnage/Services/Service_MySQL_Dunnage.cs", "md_repomix-output-code-only.html#autotoc_md271", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_AdminPartsViewModel.cs", "md_repomix-output-code-only.html#autotoc_md272", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_DetailsEntryViewModel.cs", "md_repomix-output-code-only.html#autotoc_md273", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_ManualEntryViewModel.cs", "md_repomix-output-code-only.html#autotoc_md274", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_PartSelectionViewModel.cs", "md_repomix-output-code-only.html#autotoc_md275", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminInventoryView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md276", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_AdminTypesView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md277", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_Control_IconPickerControl.xaml.cs", "md_repomix-output-code-only.html#autotoc_md278", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_QuickAddPartDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md279", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_TypeSelectionView.xaml", "md_repomix-output-code-only.html#autotoc_md280", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_TypeSelectionView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md281", null ],
        [ "File: Module_Receiving/Contracts/IService_MySQL_PackagePreferences.cs", "md_repomix-output-code-only.html#autotoc_md282", null ],
        [ "File: Module_Receiving/Contracts/IService_MySQL_Receiving.cs", "md_repomix-output-code-only.html#autotoc_md283", null ],
        [ "File: Module_Receiving/Contracts/IService_MySQL_ReceivingLine.cs", "md_repomix-output-code-only.html#autotoc_md284", null ],
        [ "File: Module_Receiving/Contracts/IService_ReceivingValidation.cs", "md_repomix-output-code-only.html#autotoc_md285", null ],
        [ "File: Module_Receiving/Contracts/IService_ReceivingWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md286", null ],
        [ "File: Module_Receiving/Data/Dao_PackageTypePreference.cs", "md_repomix-output-code-only.html#autotoc_md287", null ],
        [ "File: Module_Receiving/Data/Dao_ReceivingLoad.cs", "md_repomix-output-code-only.html#autotoc_md288", null ],
        [ "File: Module_Receiving/Models/Model_ReceivingLine.cs", "md_repomix-output-code-only.html#autotoc_md289", null ],
        [ "File: Module_Receiving/Models/Model_ReceivingLoad.cs", "md_repomix-output-code-only.html#autotoc_md290", null ],
        [ "File: Module_Receiving/Models/Model_ReceivingSession.cs", "md_repomix-output-code-only.html#autotoc_md291", null ],
        [ "File: Module_Receiving/Models/Model_ReceivingValidationResult.cs", "md_repomix-output-code-only.html#autotoc_md292", null ],
        [ "File: Module_Receiving/Models/Model_ReceivingWorkflowStepResult.cs", "md_repomix-output-code-only.html#autotoc_md293", null ],
        [ "File: Module_Receiving/Services/Service_CSVWriter.cs", "md_repomix-output-code-only.html#autotoc_md294", null ],
        [ "File: Module_Receiving/Services/Service_MySQL_PackagePreferences.cs", "md_repomix-output-code-only.html#autotoc_md295", null ],
        [ "File: Module_Receiving/Services/Service_MySQL_Receiving.cs", "md_repomix-output-code-only.html#autotoc_md296", null ],
        [ "File: Module_Receiving/Services/Service_MySQL_ReceivingLine.cs", "md_repomix-output-code-only.html#autotoc_md297", null ],
        [ "File: Module_Receiving/Services/Service_ReceivingWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md298", null ],
        [ "File: Module_Receiving/Services/Service_SessionManager.cs", "md_repomix-output-code-only.html#autotoc_md299", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_EditMode.cs", "md_repomix-output-code-only.html#autotoc_md300", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_ManualEntry.cs", "md_repomix-output-code-only.html#autotoc_md301", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_PackageType.cs", "md_repomix-output-code-only.html#autotoc_md302", null ],
        [ "File: Module_Receiving/Views/View_Receiving_ManualEntry.xaml.cs", "md_repomix-output-code-only.html#autotoc_md303", null ],
        [ "File: Module_Reporting/Contracts/IService_Reporting.cs", "md_repomix-output-code-only.html#autotoc_md304", null ],
        [ "File: Module_Routing/Constants/Constant_Routing.cs", "md_repomix-output-code-only.html#autotoc_md305", null ],
        [ "File: Module_Routing/Constants/Constant_RoutingConfiguration.cs", "md_repomix-output-code-only.html#autotoc_md306", null ],
        [ "File: Module_Routing/Data/Dao_RoutingRecipient.cs", "md_repomix-output-code-only.html#autotoc_md307", null ],
        [ "File: Module_Routing/Enums/Enum_Routing_WorkflowStep.cs", "md_repomix-output-code-only.html#autotoc_md308", null ],
        [ "File: Module_Routing/Interfaces/IDao_RoutingLabel.cs", "md_repomix-output-code-only.html#autotoc_md309", null ],
        [ "File: Module_Routing/Interfaces/IDao_RoutingLabelHistory.cs", "md_repomix-output-code-only.html#autotoc_md310", null ],
        [ "File: Module_Routing/Interfaces/IDao_RoutingRecipient.cs", "md_repomix-output-code-only.html#autotoc_md311", null ],
        [ "File: Module_Routing/Interfaces/IDao_RoutingUsageTracking.cs", "md_repomix-output-code-only.html#autotoc_md312", null ],
        [ "File: Module_Routing/Models/Model_RoutingLabelHistory.cs", "md_repomix-output-code-only.html#autotoc_md313", null ],
        [ "File: Module_Routing/Models/Model_RoutingOtherReason.cs", "md_repomix-output-code-only.html#autotoc_md314", null ],
        [ "File: Module_Routing/Models/Model_RoutingRecipient.cs", "md_repomix-output-code-only.html#autotoc_md315", null ],
        [ "File: Module_Routing/Models/Model_RoutingUsageTracking.cs", "md_repomix-output-code-only.html#autotoc_md316", null ],
        [ "File: Module_Routing/Models/Model_RoutingUserPreference.cs", "md_repomix-output-code-only.html#autotoc_md317", null ],
        [ "File: Module_Routing/Services/IRoutingInforVisualService.cs", "md_repomix-output-code-only.html#autotoc_md318", null ],
        [ "File: Module_Routing/Services/IRoutingService.cs", "md_repomix-output-code-only.html#autotoc_md319", null ],
        [ "File: Module_Routing/Services/IRoutingUsageTrackingService.cs", "md_repomix-output-code-only.html#autotoc_md320", null ],
        [ "File: Module_Routing/Services/IRoutingUserPreferenceService.cs", "md_repomix-output-code-only.html#autotoc_md321", null ],
        [ "File: Module_Routing/Views/RoutingEditModeView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md322", null ],
        [ "File: Module_Routing/Views/RoutingManualEntryView.xaml", "md_repomix-output-code-only.html#autotoc_md323", null ],
        [ "File: Module_Routing/Views/RoutingManualEntryView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md324", null ],
        [ "File: Module_Routing/Views/RoutingModeSelectionView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md325", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep2View.xaml.cs", "md_repomix-output-code-only.html#autotoc_md326", null ],
        [ "File: Module_Settings/Interfaces/IService_SettingsWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md327", null ],
        [ "File: Module_Settings/Models/Model_ConnectionTestResult.cs", "md_repomix-output-code-only.html#autotoc_md328", null ],
        [ "File: Module_Settings/Models/Model_DaoTestResult.cs", "md_repomix-output-code-only.html#autotoc_md329", null ],
        [ "File: Module_Settings/Models/Model_SettingValue.cs", "md_repomix-output-code-only.html#autotoc_md330", null ],
        [ "File: Module_Settings/Models/Model_StoredProcedureTestResult.cs", "md_repomix-output-code-only.html#autotoc_md331", null ],
        [ "File: Module_Settings/Models/Model_TableTestResult.cs", "md_repomix-output-code-only.html#autotoc_md332", null ],
        [ "File: Module_Settings/Services/Service_UserPreferences.cs", "md_repomix-output-code-only.html#autotoc_md333", null ],
        [ "File: Module_Settings/Views/View_Settings_DatabaseTest.xaml.cs", "md_repomix-output-code-only.html#autotoc_md334", null ],
        [ "File: Module_Shared/ViewModels/ViewModel_Shared_MainWindow.cs", "md_repomix-output-code-only.html#autotoc_md335", null ],
        [ "File: Module_Volvo/Contracts/IService_Volvo.cs", "md_repomix-output-code-only.html#autotoc_md336", null ],
        [ "File: Module_Volvo/Contracts/IService_VolvoMasterData.cs", "md_repomix-output-code-only.html#autotoc_md337", null ],
        [ "File: Module_Volvo/Interfaces/IDao_VolvoPart.cs", "md_repomix-output-code-only.html#autotoc_md338", null ],
        [ "File: Module_Volvo/Interfaces/IDao_VolvoShipment.cs", "md_repomix-output-code-only.html#autotoc_md339", null ],
        [ "File: Module_Volvo/Interfaces/IDao_VolvoShipmentLine.cs", "md_repomix-output-code-only.html#autotoc_md340", null ],
        [ "File: Module_Volvo/Models/Model_EmailRecipient.cs", "md_repomix-output-code-only.html#autotoc_md341", null ],
        [ "File: Module_Volvo/Models/Model_VolvoEmailData.cs", "md_repomix-output-code-only.html#autotoc_md342", null ],
        [ "File: Module_Volvo/Models/Model_VolvoPartComponent.cs", "md_repomix-output-code-only.html#autotoc_md343", null ],
        [ "File: Module_Volvo/Models/Model_VolvoShipment.cs", "md_repomix-output-code-only.html#autotoc_md344", null ],
        [ "File: Module_Volvo/Models/VolvoShipmentStatus.cs", "md_repomix-output-code-only.html#autotoc_md345", null ],
        [ "File: Module_Volvo/Services/IService_VolvoAuthorization.cs", "md_repomix-output-code-only.html#autotoc_md346", null ],
        [ "File: Module_Volvo/Views/VolvoPartAddEditDialog.xaml", "md_repomix-output-code-only.html#autotoc_md347", null ],
        [ "File: MTM_Receiving_Application.Tests/Fixtures/DatabaseFixture.cs", "md_repomix-output-code-only.html#autotoc_md348", null ],
        [ "File: MTM_Receiving_Application.Tests/Fixtures/ServiceCollectionFixture.cs", "md_repomix-output-code-only.html#autotoc_md349", null ],
        [ "File: MTM_Receiving_Application.Tests/Helpers/TestHelper.cs", "md_repomix-output-code-only.html#autotoc_md350", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_BooleanToVisibility_Tests.cs", "md_repomix-output-code-only.html#autotoc_md351", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_BoolToString_Tests.cs", "md_repomix-output-code-only.html#autotoc_md352", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_DecimalToString_Tests.cs", "md_repomix-output-code-only.html#autotoc_md353", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_DoubleToDecimal_Tests.cs", "md_repomix-output-code-only.html#autotoc_md354", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_EmptyStringToVisibility_Tests.cs", "md_repomix-output-code-only.html#autotoc_md355", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_EnumToVisibility_Tests.cs", "md_repomix-output-code-only.html#autotoc_md356", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_IconCodeToGlyph_Tests.cs", "md_repomix-output-code-only.html#autotoc_md357", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_IntToVisibility_Tests.cs", "md_repomix-output-code-only.html#autotoc_md358", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_LoadNumberToOneBased_Tests.cs", "md_repomix-output-code-only.html#autotoc_md359", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_StringFormat_Tests.cs", "md_repomix-output-code-only.html#autotoc_md360", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/NullableDoubleToDoubleConverter_Tests.cs", "md_repomix-output-code-only.html#autotoc_md361", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Defaults/InforVisualDefaults_Tests.cs", "md_repomix-output-code-only.html#autotoc_md362", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Defaults/WorkstationDefaults_Tests.cs", "md_repomix-output-code-only.html#autotoc_md363", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Helpers/Database/Helper_Database_StoredProcedure_Tests.cs", "md_repomix-output-code-only.html#autotoc_md364", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Helpers/Database/Helper_Database_Variables_Tests.cs", "md_repomix-output-code-only.html#autotoc_md365", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Systems/Model_AuthenticationResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md366", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Systems/Model_User_Tests.cs", "md_repomix-output-code-only.html#autotoc_md367", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Systems/Model_ValidationResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md368", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Services/Authentication/Service_Authentication_Tests.cs", "md_repomix-output-code-only.html#autotoc_md369", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Services/Authentication/Service_UserSessionManager_Tests.cs", "md_repomix-output-code-only.html#autotoc_md370", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Services/Database/Service_ErrorHandler_Tests.cs", "md_repomix-output-code-only.html#autotoc_md371", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Services/Help/Service_Help_Tests.cs", "md_repomix-output-code-only.html#autotoc_md372", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Services/UI/Service_ViewModelRegistry_Tests.cs", "md_repomix-output-code-only.html#autotoc_md373", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_Application_Variables_Tests.cs", "md_repomix-output-code-only.html#autotoc_md374", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_CSVDeleteResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md375", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_CSVExistenceResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md376", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_CSVWriteResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md377", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_InforVisualPart_Tests.cs", "md_repomix-output-code-only.html#autotoc_md378", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_InforVisualPO_Tests.cs", "md_repomix-output-code-only.html#autotoc_md379", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_PackageTypePreference_Tests.cs", "md_repomix-output-code-only.html#autotoc_md380", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_ReceivingLine_Tests.cs", "md_repomix-output-code-only.html#autotoc_md381", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_ReceivingLoad_Tests.cs", "md_repomix-output-code-only.html#autotoc_md382", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_ReceivingSession_Tests.cs", "md_repomix-output-code-only.html#autotoc_md383", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_ReceivingValidationResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md384", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_ReceivingWorkflowStepResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md385", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_SaveResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md386", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_UserPreference_Tests.cs", "md_repomix-output-code-only.html#autotoc_md387", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Models/Model_WorkflowStepResult_Tests.cs", "md_repomix-output-code-only.html#autotoc_md388", null ],
        [ "File: Module_Core/Contracts/Services/IService_Authentication.cs", "md_repomix-output-code-only.html#autotoc_md389", null ],
        [ "File: Module_Core/Converters/Converter_EnumToVisibility.cs", "md_repomix-output-code-only.html#autotoc_md390", null ],
        [ "File: Module_Core/Converters/Converter_IntToVisibility.cs", "md_repomix-output-code-only.html#autotoc_md391", null ],
        [ "File: Module_Core/Converters/NullableDoubleToDoubleConverter.cs", "md_repomix-output-code-only.html#autotoc_md392", null ],
        [ "File: Module_Core/Helpers/Database/Helper_Database_StoredProcedure.cs", "md_repomix-output-code-only.html#autotoc_md393", null ],
        [ "File: Module_Core/Models/Systems/Model_User.cs", "md_repomix-output-code-only.html#autotoc_md394", null ],
        [ "File: Module_Core/Services/Startup/Service_OnStartup_AppLifecycle.cs", "md_repomix-output-code-only.html#autotoc_md395", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageCustomField.cs", "md_repomix-output-code-only.html#autotoc_md396", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageLoad.cs", "md_repomix-output-code-only.html#autotoc_md397", null ],
        [ "File: Module_Dunnage/Data/Dao_DunnageType.cs", "md_repomix-output-code-only.html#autotoc_md398", null ],
        [ "File: Module_Dunnage/Data/Dao_InventoriedDunnage.cs", "md_repomix-output-code-only.html#autotoc_md399", null ],
        [ "File: Module_Dunnage/Services/Service_DunnageAdminWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md400", null ],
        [ "File: Module_Dunnage/Services/Service_DunnageCSVWriter.cs", "md_repomix-output-code-only.html#autotoc_md401", null ],
        [ "File: Module_Dunnage/Services/Service_DunnageWorkflow.cs", "md_repomix-output-code-only.html#autotoc_md402", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_AddTypeDialogViewModel.cs", "md_repomix-output-code-only.html#autotoc_md403", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_AdminMainViewModel.cs", "md_repomix-output-code-only.html#autotoc_md404", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_AdminTypesViewModel.cs", "md_repomix-output-code-only.html#autotoc_md405", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_EditModeViewModel.cs", "md_repomix-output-code-only.html#autotoc_md406", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_QuantityEntryViewModel.cs", "md_repomix-output-code-only.html#autotoc_md407", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_TypeSelectionViewModel.cs", "md_repomix-output-code-only.html#autotoc_md408", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_WorkflowView.xaml", "md_repomix-output-code-only.html#autotoc_md409", null ],
        [ "File: Module_Receiving/Data/Dao_ReceivingLine.cs", "md_repomix-output-code-only.html#autotoc_md410", null ],
        [ "File: Module_Receiving/Services/Service_ReceivingValidation.cs", "md_repomix-output-code-only.html#autotoc_md411", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_HeatLot.cs", "md_repomix-output-code-only.html#autotoc_md412", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_LoadEntry.cs", "md_repomix-output-code-only.html#autotoc_md413", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_ModeSelection.cs", "md_repomix-output-code-only.html#autotoc_md414", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_Review.cs", "md_repomix-output-code-only.html#autotoc_md415", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_WeightQuantity.cs", "md_repomix-output-code-only.html#autotoc_md416", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_Workflow.cs", "md_repomix-output-code-only.html#autotoc_md417", null ],
        [ "File: Module_Receiving/Views/View_Receiving_Workflow.xaml.cs", "md_repomix-output-code-only.html#autotoc_md418", null ],
        [ "File: Module_Reporting/Services/Service_Reporting.cs", "md_repomix-output-code-only.html#autotoc_md419", null ],
        [ "File: Module_Reporting/ViewModels/ViewModel_Reporting_Main.cs", "md_repomix-output-code-only.html#autotoc_md420", null ],
        [ "File: Module_Routing/Converters/IntToFontWeightConverter.cs", "md_repomix-output-code-only.html#autotoc_md421", null ],
        [ "File: Module_Routing/Converters/IntToProgressBrushConverter.cs", "md_repomix-output-code-only.html#autotoc_md422", null ],
        [ "File: Module_Routing/Converters/NullToBooleanConverter.cs", "md_repomix-output-code-only.html#autotoc_md423", null ],
        [ "File: Module_Routing/Data/Dao_RoutingOtherReason.cs", "md_repomix-output-code-only.html#autotoc_md424", null ],
        [ "File: Module_Routing/Data/Dao_RoutingUsageTracking.cs", "md_repomix-output-code-only.html#autotoc_md425", null ],
        [ "File: Module_Routing/Data/Dao_RoutingUserPreference.cs", "md_repomix-output-code-only.html#autotoc_md426", null ],
        [ "File: Module_Routing/Models/Model_InforVisualPOLine.cs", "md_repomix-output-code-only.html#autotoc_md427", null ],
        [ "File: Module_Routing/Models/Model_RoutingLabel.cs", "md_repomix-output-code-only.html#autotoc_md428", null ],
        [ "File: Module_Routing/Services/IRoutingRecipientService.cs", "md_repomix-output-code-only.html#autotoc_md429", null ],
        [ "File: Module_Routing/Services/RoutingRecipientService.cs", "md_repomix-output-code-only.html#autotoc_md430", null ],
        [ "File: Module_Routing/Services/RoutingUserPreferenceService.cs", "md_repomix-output-code-only.html#autotoc_md431", null ],
        [ "File: Module_Routing/ViewModels/RoutingEditModeViewModel.cs", "md_repomix-output-code-only.html#autotoc_md432", null ],
        [ "File: Module_Routing/ViewModels/RoutingManualEntryViewModel.cs", "md_repomix-output-code-only.html#autotoc_md433", null ],
        [ "File: Module_Routing/Views/RoutingModeSelectionView.xaml", "md_repomix-output-code-only.html#autotoc_md434", null ],
        [ "File: Module_Routing/Views/RoutingWizardContainerView.xaml", "md_repomix-output-code-only.html#autotoc_md435", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep2View.xaml", "md_repomix-output-code-only.html#autotoc_md436", null ],
        [ "File: Module_Settings/Data/Dao_PackageTypeMappings.cs", "md_repomix-output-code-only.html#autotoc_md437", null ],
        [ "File: Module_Settings/Data/Dao_ScheduledReport.cs", "md_repomix-output-code-only.html#autotoc_md438", null ],
        [ "File: Module_Settings/Data/Dao_SystemSettings.cs", "md_repomix-output-code-only.html#autotoc_md439", null ],
        [ "File: Module_Settings/Data/Dao_UserSettings.cs", "md_repomix-output-code-only.html#autotoc_md440", null ],
        [ "File: Module_Settings/Models/Model_PackageType.cs", "md_repomix-output-code-only.html#autotoc_md441", null ],
        [ "File: Module_Settings/Models/Model_PackageTypeMapping.cs", "md_repomix-output-code-only.html#autotoc_md442", null ],
        [ "File: Module_Settings/Models/Model_RoutingRule.cs", "md_repomix-output-code-only.html#autotoc_md443", null ],
        [ "File: Module_Settings/Models/Model_ScheduledReport.cs", "md_repomix-output-code-only.html#autotoc_md444", null ],
        [ "File: Module_Settings/Models/Model_SettingsAuditLog.cs", "md_repomix-output-code-only.html#autotoc_md445", null ],
        [ "File: Module_Settings/Models/Model_SystemSetting.cs", "md_repomix-output-code-only.html#autotoc_md446", null ],
        [ "File: Module_Settings/Models/Model_UserSetting.cs", "md_repomix-output-code-only.html#autotoc_md447", null ],
        [ "File: Module_Settings/Views/View_Settings_DatabaseTest.xaml", "md_repomix-output-code-only.html#autotoc_md448", null ],
        [ "File: Module_Volvo/Models/Model_VolvoPart.cs", "md_repomix-output-code-only.html#autotoc_md449", null ],
        [ "File: Module_Volvo/Models/Model_VolvoSetting.cs", "md_repomix-output-code-only.html#autotoc_md450", null ],
        [ "File: Module_Volvo/Services/Service_VolvoAuthorization.cs", "md_repomix-output-code-only.html#autotoc_md451", null ],
        [ "File: Module_Volvo/Views/View_Volvo_History.xaml", "md_repomix-output-code-only.html#autotoc_md452", null ],
        [ "File: Module_Volvo/Views/View_Volvo_Settings.xaml", "md_repomix-output-code-only.html#autotoc_md453", null ],
        [ "File: Module_Volvo/Views/View_Volvo_ShipmentEntry.xaml.cs", "md_repomix-output-code-only.html#autotoc_md454", null ],
        [ "File: Module_Volvo/Views/VolvoPartAddEditDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md455", null ],
        [ "File: Module_Volvo/Views/VolvoShipmentEditDialog.xaml.cs", "md_repomix-output-code-only.html#autotoc_md456", null ],
        [ "File: MTM_Receiving_Application.Tests/GlobalUsings.cs", "md_repomix-output-code-only.html#autotoc_md457", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Converters/Converter_DecimalToInt_Tests.cs", "md_repomix-output-code-only.html#autotoc_md458", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Core/Model_Dao_Result_Factory_Tests.cs", "md_repomix-output-code-only.html#autotoc_md459", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Systems/Model_UserSession_Tests.cs", "md_repomix-output-code-only.html#autotoc_md460", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Models/Systems/Model_WorkstationConfig_Tests.cs", "md_repomix-output-code-only.html#autotoc_md461", null ],
        [ "File: Module_Core/Models/Systems/Model_WorkstationConfig.cs", "md_repomix-output-code-only.html#autotoc_md462", null ],
        [ "File: Module_Core/Services/Authentication/Service_Authentication.cs", "md_repomix-output-code-only.html#autotoc_md463", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_AdminInventoryViewModel.cs", "md_repomix-output-code-only.html#autotoc_md464", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_ModeSelectionViewModel.cs", "md_repomix-output-code-only.html#autotoc_md465", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_ReviewViewModel.cs", "md_repomix-output-code-only.html#autotoc_md466", null ],
        [ "File: Module_Dunnage/ViewModels/ViewModel_Dunnage_WorkFlowViewModel.cs", "md_repomix-output-code-only.html#autotoc_md467", null ],
        [ "File: Module_Receiving/ViewModels/ViewModel_Receiving_POEntry.cs", "md_repomix-output-code-only.html#autotoc_md468", null ],
        [ "File: Module_Reporting/Data/Dao_Reporting.cs", "md_repomix-output-code-only.html#autotoc_md469", null ],
        [ "File: Module_Routing/Services/RoutingUsageTrackingService.cs", "md_repomix-output-code-only.html#autotoc_md470", null ],
        [ "File: Module_Routing/ViewModels/RoutingModeSelectionViewModel.cs", "md_repomix-output-code-only.html#autotoc_md471", null ],
        [ "File: Module_Routing/ViewModels/RoutingWizardStep2ViewModel.cs", "md_repomix-output-code-only.html#autotoc_md472", null ],
        [ "File: Module_Routing/ViewModels/RoutingWizardStep3ViewModel.cs", "md_repomix-output-code-only.html#autotoc_md473", null ],
        [ "File: Module_Routing/Views/RoutingEditModeView.xaml", "md_repomix-output-code-only.html#autotoc_md474", null ],
        [ "File: Module_Settings/Data/Dao_PackageType.cs", "md_repomix-output-code-only.html#autotoc_md475", null ],
        [ "File: Module_Settings/Data/Dao_RoutingRule.cs", "md_repomix-output-code-only.html#autotoc_md476", null ],
        [ "File: Module_Settings/Data/Dao_SettingsAuditLog.cs", "md_repomix-output-code-only.html#autotoc_md477", null ],
        [ "File: Module_Volvo/Data/Dao_VolvoPartComponent.cs", "md_repomix-output-code-only.html#autotoc_md478", null ],
        [ "File: Module_Volvo/ViewModels/ViewModel_Volvo_Settings.cs", "md_repomix-output-code-only.html#autotoc_md479", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Core/Data/Authentication/Dao_User_Tests.cs", "md_repomix-output-code-only.html#autotoc_md480", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Dunnage/Data/Dao_DunnageLoad_Tests.cs", "md_repomix-output-code-only.html#autotoc_md481", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLine_Tests.cs", "md_repomix-output-code-only.html#autotoc_md482", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Receiving/Data/Dao_ReceivingLoad_Tests.cs", "md_repomix-output-code-only.html#autotoc_md483", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Routing/Data/Dao_RoutingLabel_Tests.cs", "md_repomix-output-code-only.html#autotoc_md484", null ],
        [ "File: MTM_Receiving_Application.Tests/Module_Settings/Data/Dao_PackageType_Tests.cs", "md_repomix-output-code-only.html#autotoc_md485", null ],
        [ "File: MTM_Receiving_Application.Tests/UnitTest1.cs", "md_repomix-output-code-only.html#autotoc_md486", null ],
        [ "File: Module_Core/Helpers/Database/Helper_Database_Variables.cs", "md_repomix-output-code-only.html#autotoc_md487", null ],
        [ "File: Module_Dunnage/Views/View_Dunnage_WorkflowView.xaml.cs", "md_repomix-output-code-only.html#autotoc_md488", null ],
        [ "File: Module_Routing/Data/Dao_RoutingLabel.cs", "md_repomix-output-code-only.html#autotoc_md489", null ],
        [ "File: Module_Routing/Data/Dao_RoutingLabelHistory.cs", "md_repomix-output-code-only.html#autotoc_md490", null ],
        [ "File: Module_Routing/Services/RoutingInforVisualService.cs", "md_repomix-output-code-only.html#autotoc_md491", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep3View.xaml", "md_repomix-output-code-only.html#autotoc_md492", null ],
        [ "File: Module_Volvo/Data/Dao_VolvoPart.cs", "md_repomix-output-code-only.html#autotoc_md493", null ],
        [ "File: Module_Volvo/Data/Dao_VolvoSettings.cs", "md_repomix-output-code-only.html#autotoc_md494", null ],
        [ "File: Module_Volvo/Data/Dao_VolvoShipmentLine.cs", "md_repomix-output-code-only.html#autotoc_md495", null ],
        [ "File: Module_Volvo/Services/Service_VolvoMasterData.cs", "md_repomix-output-code-only.html#autotoc_md496", null ],
        [ "File: Module_Volvo/ViewModels/ViewModel_Volvo_History.cs", "md_repomix-output-code-only.html#autotoc_md497", null ],
        [ "File: Module_Volvo/Views/VolvoShipmentEditDialog.xaml", "md_repomix-output-code-only.html#autotoc_md498", null ],
        [ "File: Module_Routing/Data/Dao_InforVisualPO.cs", "md_repomix-output-code-only.html#autotoc_md499", null ],
        [ "File: Module_Routing/Services/RoutingService.cs", "md_repomix-output-code-only.html#autotoc_md500", null ],
        [ "File: Module_Routing/ViewModels/RoutingWizardContainerViewModel.cs", "md_repomix-output-code-only.html#autotoc_md501", null ],
        [ "File: Module_Routing/Views/RoutingWizardStep1View.xaml", "md_repomix-output-code-only.html#autotoc_md502", null ],
        [ "File: Module_Volvo/Data/Dao_VolvoShipment.cs", "md_repomix-output-code-only.html#autotoc_md503", null ],
        [ "File: Module_Volvo/Models/Model_VolvoShipmentLine.cs", "md_repomix-output-code-only.html#autotoc_md504", null ],
        [ "File: MainWindow.xaml", "md_repomix-output-code-only.html#autotoc_md505", null ],
        [ "File: Module_Routing/ViewModels/RoutingWizardStep1ViewModel.cs", "md_repomix-output-code-only.html#autotoc_md506", null ],
        [ "File: Module_Settings/ViewModels/ViewModel_Settings_DatabaseTest.cs", "md_repomix-output-code-only.html#autotoc_md507", null ],
        [ "File: Module_Volvo/Views/View_Volvo_ShipmentEntry.xaml", "md_repomix-output-code-only.html#autotoc_md508", null ],
        [ "File: Module_Core/Data/Authentication/Dao_User.cs", "md_repomix-output-code-only.html#autotoc_md509", null ],
        [ "File: Module_Volvo/Services/Service_Volvo.cs", "md_repomix-output-code-only.html#autotoc_md510", null ],
        [ "File: Module_Volvo/ViewModels/ViewModel_Volvo_ShipmentEntry.cs", "md_repomix-output-code-only.html#autotoc_md511", null ],
        [ "File: MainWindow.xaml.cs", "md_repomix-output-code-only.html#autotoc_md512", null ],
        [ "File: App.xaml.cs", "md_repomix-output-code-only.html#autotoc_md513", null ]
      ] ]
    ] ],
    [ "repomix-output-copilot-docs", "md_repomix-output-copilot-docs.html", [
      [ "File Summary", "md_repomix-output-copilot-docs.html#autotoc_md514", [
        [ "Purpose", "md_repomix-output-copilot-docs.html#autotoc_md515", null ],
        [ "File Format", "md_repomix-output-copilot-docs.html#autotoc_md516", null ],
        [ "Usage Guidelines", "md_repomix-output-copilot-docs.html#autotoc_md517", null ],
        [ "Notes", "md_repomix-output-copilot-docs.html#autotoc_md518", null ]
      ] ],
      [ "User Provided Header", "md_repomix-output-copilot-docs.html#autotoc_md519", null ],
      [ "Directory Structure", "md_repomix-output-copilot-docs.html#autotoc_md520", null ],
      [ "Files", "md_repomix-output-copilot-docs.html#autotoc_md521", null ]
    ] ],
    [ "Namespaces", "namespaces.html", [
      [ "Namespace List", "namespaces.html", "namespaces_dup" ]
    ] ],
    [ "Data Structures", "annotated.html", [
      [ "Data Structures", "annotated.html", "annotated_dup" ],
      [ "Data Structure Index", "classes.html", null ],
      [ "Class Hierarchy", "hierarchy.html", "hierarchy" ],
      [ "Data Fields", "functions.html", [
        [ "All", "functions.html", null ],
        [ "Functions", "functions_func.html", null ],
        [ "Properties", "functions_prop.html", null ]
      ] ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ]
    ] ]
  ] ]
];

var NAVTREEINDEX =
[
"_app_8xaml_8cs.html",
"md_repomix-output-code-only.html#autotoc_md236",
"md_repomix-output-code-only.html#autotoc_md486"
];

var SYNCONMSG = 'click to disable panel synchronization';
var SYNCOFFMSG = 'click to enable panel synchronization';
var LISTOFALLMEMBERS = 'List of all members';