// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_WorkstationConfig.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Defaults;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_WorkstationConfig"/>.
/// Tests workstation configuration with computed properties for timeout and type detection.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_WorkstationConfigTests
{
    [Fact]
    public void Constructor_DefaultComputerNameIsEnvironmentMachineName()
    {
        var sut = new Model_WorkstationConfig();

        sut.ComputerName.Should().Be(Environment.MachineName);
    }

    [Fact]
    public void Constructor_WithComputerName_SetsComputerName()
    {
        var sut = new Model_WorkstationConfig("CUSTOM-PC");

        sut.ComputerName.Should().Be("CUSTOM-PC");
    }

    [Fact]
    public void Constructor_WithNullComputerName_UsesEnvironmentMachineName()
    {
        var sut = new Model_WorkstationConfig(null);

        sut.ComputerName.Should().Be(Environment.MachineName);
    }

    [Fact]
    public void WorkstationType_CanBeSet()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = "personal_workstation"
        };

        sut.WorkstationType.Should().Be("personal_workstation");
    }

    [Fact]
    public void Description_CanBeSet()
    {
        var sut = new Model_WorkstationConfig
        {
            Description = "Shipping Department Terminal 1"
        };

        sut.Description.Should().Be("Shipping Department Terminal 1");
    }

    [Fact]
    public void IsSharedTerminal_ReturnsTrue_WhenWorkstationTypeIsSharedTerminal()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = WorkstationDefaults.SharedTerminalWorkstationType
        };

        sut.IsSharedTerminal.Should().BeTrue();
        sut.IsPersonalWorkstation.Should().BeFalse();
    }

    [Fact]
    public void IsPersonalWorkstation_ReturnsTrue_WhenWorkstationTypeIsPersonalWorkstation()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = WorkstationDefaults.PersonalWorkstationWorkstationType
        };

        sut.IsPersonalWorkstation.Should().BeTrue();
        sut.IsSharedTerminal.Should().BeFalse();
    }

    [Fact]
    public void TimeoutDuration_Returns15Minutes_ForSharedTerminal()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = WorkstationDefaults.SharedTerminalWorkstationType
        };

        sut.TimeoutDuration.Should().Be(TimeSpan.FromMinutes(WorkstationDefaults.SharedTerminalTimeoutMinutes));
    }

    [Fact]
    public void TimeoutDuration_Returns30Minutes_ForPersonalWorkstation()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = WorkstationDefaults.PersonalWorkstationWorkstationType
        };

        sut.TimeoutDuration.Should().Be(TimeSpan.FromMinutes(WorkstationDefaults.PersonalWorkstationTimeoutMinutes));
    }

    [Fact]
    public void TimeoutDuration_Returns30Minutes_WhenWorkstationTypeIsUnknown()
    {
        var sut = new Model_WorkstationConfig
        {
            WorkstationType = "unknown_type"
        };

        sut.TimeoutDuration.Should().Be(TimeSpan.FromMinutes(WorkstationDefaults.PersonalWorkstationTimeoutMinutes));
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var sut = new Model_WorkstationConfig("WS-001")
        {
            WorkstationType = "shared_terminal",
            Description = "Production Floor Terminal"
        };

        sut.ComputerName.Should().Be("WS-001");
        sut.WorkstationType.Should().Be("shared_terminal");
        sut.Description.Should().Be("Production Floor Terminal");
        sut.IsSharedTerminal.Should().BeTrue();
    }
}
