// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_ValidationResult.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_ValidationResult"/>.
/// Tests validation result model with factory methods.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_ValidationResultTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_ValidationResult();

        sut.IsValid.Should().BeFalse();
        sut.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void IsValid_CanBeSet()
    {
        var sut = new Model_ValidationResult
        {
            IsValid = true
        };

        sut.IsValid.Should().BeTrue();
    }

    [Fact]
    public void ErrorMessage_CanBeSet()
    {
        var sut = new Model_ValidationResult
        {
            ErrorMessage = "Test error"
        };

        sut.ErrorMessage.Should().Be("Test error");
    }

    [Fact]
    public void Valid_ReturnsValidResult()
    {
        var result = Model_ValidationResult.Valid();

        result.IsValid.Should().BeTrue();
        result.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void Invalid_WithMessage_ReturnsInvalidResultWithMessage()
    {
        var result = Model_ValidationResult.Invalid("Test error");

        result.IsValid.Should().BeFalse();
        result.ErrorMessage.Should().Be("Test error");
    }

    [Fact]
    public void Invalid_WithNullMessage_UsesDefaultMessage()
    {
        var result = Model_ValidationResult.Invalid(null);

        result.IsValid.Should().BeFalse();
        result.ErrorMessage.Should().Be("Validation failed.");
    }

    [Fact]
    public void Invalid_WithEmptyMessage_UsesDefaultMessage()
    {
        var result = Model_ValidationResult.Invalid(string.Empty);

        result.IsValid.Should().BeFalse();
        result.ErrorMessage.Should().Be("Validation failed.");
    }

    [Fact]
    public void Invalid_WithWhitespaceMessage_UsesDefaultMessage()
    {
        var result = Model_ValidationResult.Invalid("   ");

        result.IsValid.Should().BeFalse();
        result.ErrorMessage.Should().Be("Validation failed.");
    }

    [Fact]
    public void Valid_ThenInvalid_CreatesIndependentInstances()
    {
        var validResult = Model_ValidationResult.Valid();
        var invalidResult = Model_ValidationResult.Invalid("Error");

        validResult.IsValid.Should().BeTrue();
        invalidResult.IsValid.Should().BeFalse();
        invalidResult.ErrorMessage.Should().Be("Error");
        validResult.ErrorMessage.Should().BeEmpty();
    }
}
