// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_AppSettings.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_AppSettings"/>.
/// Tests application settings loaded from appsettings.json.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_AppSettingsTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_AppSettings();

        sut.UseInforVisualMockData.Should().BeTrue();
        sut.Environment.Should().Be("Development");
    }

    [Fact]
    public void UseInforVisualMockData_CanBeSet()
    {
        var sut = new Model_AppSettings { UseInforVisualMockData = false };

        sut.UseInforVisualMockData.Should().BeFalse();
    }

    [Theory]
    [InlineData("Development")]
    [InlineData("Production")]
    [InlineData("Staging")]
    [InlineData("Testing")]
    public void Environment_CanBeSetToVariousEnvironments(string environment)
    {
        var sut = new Model_AppSettings { Environment = environment };

        sut.Environment.Should().Be(environment);
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var sut = new Model_AppSettings
        {
            UseInforVisualMockData = false,
            Environment = "Production"
        };

        sut.UseInforVisualMockData.Should().BeFalse();
        sut.Environment.Should().Be("Production");
    }
}
