// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_User.cs
// </auto-generated>

#nullable enable

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_User"/>.
/// Tests user/employee model with database fields and computed properties.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_UserTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_User();

        sut.EmployeeNumber.Should().Be(0);
        sut.WindowsUsername.Should().BeEmpty();
        sut.FullName.Should().BeEmpty();
        sut.Pin.Should().BeEmpty();
        sut.Department.Should().BeEmpty();
        sut.Shift.Should().BeEmpty();
        sut.IsActive.Should().BeTrue();
        sut.VisualUsername.Should().BeNull();
        sut.VisualPassword.Should().BeNull();
        sut.DefaultReceivingMode.Should().BeNull();
        sut.DefaultDunnageMode.Should().BeNull();
        sut.CreatedBy.Should().BeNull();
    }

    [Fact]
    public void EmployeeNumber_CanBeSet()
    {
        var sut = new Model_User
        {
            EmployeeNumber = 12345
        };

        sut.EmployeeNumber.Should().Be(12345);
    }

    [Fact]
    public void WindowsUsername_CanBeSet()
    {
        var sut = new Model_User
        {
            WindowsUsername = "DOMAIN\\testuser"
        };

        sut.WindowsUsername.Should().Be("DOMAIN\\testuser");
    }

    [Fact]
    public void FullName_CanBeSet()
    {
        var sut = new Model_User
        {
            FullName = "John Doe"
        };

        sut.FullName.Should().Be("John Doe");
    }

    [Fact]
    public void Pin_CanBeSet()
    {
        var sut = new Model_User
        {
            Pin = "1234"
        };

        sut.Pin.Should().Be("1234");
    }

    [Theory]
    [InlineData("Production")]
    [InlineData("Quality")]
    [InlineData("Shipping")]
    public void Department_CanBeSetToVariousValues(string department)
    {
        var sut = new Model_User
        {
            Department = department
        };

        sut.Department.Should().Be(department);
    }

    [Theory]
    [InlineData("1st Shift")]
    [InlineData("2nd Shift")]
    [InlineData("3rd Shift")]
    public void Shift_CanBeSetToValidShifts(string shift)
    {
        var sut = new Model_User
        {
            Shift = shift
        };

        sut.Shift.Should().Be(shift);
    }

    [Fact]
    public void IsActive_CanBeToggled()
    {
        var sut = new Model_User
        {
            IsActive = false
        };

        sut.IsActive.Should().BeFalse();
    }

    [Fact]
    public void VisualCredentials_CanBeSet()
    {
        var sut = new Model_User
        {
            VisualUsername = "visualuser",
            VisualPassword = "visualpass"
        };

        sut.VisualUsername.Should().Be("visualuser");
        sut.VisualPassword.Should().Be("visualpass");
    }

    [Theory]
    [InlineData("guided")]
    [InlineData("manual")]
    [InlineData(null)]
    public void DefaultReceivingMode_CanBeSetToValidModes(string? mode)
    {
        var sut = new Model_User
        {
            DefaultReceivingMode = mode
        };

        sut.DefaultReceivingMode.Should().Be(mode);
    }

    [Theory]
    [InlineData("guided")]
    [InlineData("manual")]
    [InlineData("edit")]
    [InlineData(null)]
    public void DefaultDunnageMode_CanBeSetToValidModes(string? mode)
    {
        var sut = new Model_User
        {
            DefaultDunnageMode = mode
        };

        sut.DefaultDunnageMode.Should().Be(mode);
    }

    [Fact]
    public void DisplayName_ReturnsFormattedNameWithEmployeeNumber()
    {
        var sut = new Model_User
        {
            FullName = "John Doe",
            EmployeeNumber = 12345
        };

        sut.DisplayName.Should().Be("John Doe (Emp #12345)");
    }

    [Fact]
    public void DisplayName_WithEmptyName_ReturnsFormattedEmployeeNumber()
    {
        var sut = new Model_User
        {
            FullName = string.Empty,
            EmployeeNumber = 999
        };

        sut.DisplayName.Should().Be(" (Emp #999)");
    }

    [Fact]
    public void CreatedDate_CanBeSet()
    {
        var date = new DateTime(2025, 1, 15);
        var sut = new Model_User
        {
            CreatedDate = date
        };

        sut.CreatedDate.Should().Be(date);
    }

    [Fact]
    public void ModifiedDate_CanBeSet()
    {
        var date = new DateTime(2025, 1, 19);
        var sut = new Model_User
        {
            ModifiedDate = date
        };

        sut.ModifiedDate.Should().Be(date);
    }

    [Fact]
    public void CreatedBy_CanBeSet()
    {
        var sut = new Model_User
        {
            CreatedBy = "DOMAIN\\admin"
        };

        sut.CreatedBy.Should().Be("DOMAIN\\admin");
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var sut = new Model_User
        {
            EmployeeNumber = 12345,
            WindowsUsername = "DOMAIN\\jdoe",
            FullName = "John Doe",
            Pin = "1234",
            Department = "Production",
            Shift = "1st Shift",
            IsActive = true,
            VisualUsername = "jdoe_visual",
            VisualPassword = "pass123",
            DefaultReceivingMode = "guided",
            DefaultDunnageMode = "manual",
            CreatedDate = new DateTime(2025, 1, 1),
            ModifiedDate = new DateTime(2025, 1, 15),
            CreatedBy = "DOMAIN\\admin"
        };

        sut.EmployeeNumber.Should().Be(12345);
        sut.WindowsUsername.Should().Be("DOMAIN\\jdoe");
        sut.FullName.Should().Be("John Doe");
        sut.Pin.Should().Be("1234");
        sut.Department.Should().Be("Production");
        sut.Shift.Should().Be("1st Shift");
        sut.IsActive.Should().BeTrue();
        sut.VisualUsername.Should().Be("jdoe_visual");
        sut.VisualPassword.Should().Be("pass123");
        sut.DisplayName.Should().Be("John Doe (Emp #12345)");
    }
}
