// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/InforVisual/Model_InforVisualConnection.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Defaults;
using MTM_Receiving_Application.Module_Core.Models.InforVisual;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_InforVisualConnection"/>.
/// Tests Infor Visual database connection configuration with READ-ONLY connection string generation.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_InforVisualConnectionTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_InforVisualConnection();

        sut.Server.Should().Be(InforVisualDefaults.DefaultServer);
        sut.Database.Should().Be(InforVisualDefaults.DefaultDatabase);
        sut.UserId.Should().Be("SHOP2");
        sut.Password.Should().Be("SHOP");
        sut.SiteId.Should().Be(InforVisualDefaults.DefaultSiteId);
    }

    [Fact]
    public void Server_CanBeSet()
    {
        var sut = new Model_InforVisualConnection { Server = "CustomServer" };

        sut.Server.Should().Be("CustomServer");
    }

    [Fact]
    public void Database_CanBeSet()
    {
        var sut = new Model_InforVisualConnection { Database = "CustomDB" };

        sut.Database.Should().Be("CustomDB");
    }

    [Fact]
    public void UserId_CanBeSet()
    {
        var sut = new Model_InforVisualConnection { UserId = "CustomUser" };

        sut.UserId.Should().Be("CustomUser");
    }

    [Fact]
    public void Password_CanBeSet()
    {
        var sut = new Model_InforVisualConnection { Password = "CustomPass" };

        sut.Password.Should().Be("CustomPass");
    }

    [Fact]
    public void SiteId_CanBeSet()
    {
        var sut = new Model_InforVisualConnection { SiteId = "SITE-003" };

        sut.SiteId.Should().Be("SITE-003");
    }

    [Fact]
    public void GetConnectionString_WithDefaultValues_ReturnsConnectionStringWithReadOnlyIntent()
    {
        var sut = new Model_InforVisualConnection();
        var connectionString = sut.GetConnectionString();

        connectionString.Should().Contain("Server=");
        connectionString.Should().Contain("Database=");
        connectionString.Should().Contain("User Id=SHOP2");
        connectionString.Should().Contain("Password=SHOP");
        connectionString.Should().Contain("TrustServerCertificate=True");
        connectionString.Should().Contain("ApplicationIntent=ReadOnly");
    }

    [Fact]
    public void GetConnectionString_WithCustomValues_ReturnsCorrectConnectionString()
    {
        var sut = new Model_InforVisualConnection
        {
            Server = "CustomServer",
            Database = "CustomDB",
            UserId = "CustomUser",
            Password = "CustomPass"
        };

        var connectionString = sut.GetConnectionString();

        connectionString.Should().Contain("Server=CustomServer");
        connectionString.Should().Contain("Database=CustomDB");
        connectionString.Should().Contain("User Id=CustomUser");
        connectionString.Should().Contain("Password=CustomPass");
    }

    [Fact]
    public void GetConnectionString_AlwaysIncludesReadOnlyIntent()
    {
        var sut = new Model_InforVisualConnection
        {
            Server = "TestServer",
            Database = "TestDB"
        };

        var connectionString = sut.GetConnectionString();

        connectionString.Should().Contain("ApplicationIntent=ReadOnly",
            "Infor Visual connections must be READ-ONLY");
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var sut = new Model_InforVisualConnection
        {
            Server = "PROD-SERVER",
            Database = "VISUAL_PROD",
            UserId = "PRODUSER",
            Password = "PRODPASS",
            SiteId = "002"
        };

        sut.Server.Should().Be("PROD-SERVER");
        sut.Database.Should().Be("VISUAL_PROD");
        sut.UserId.Should().Be("PRODUSER");
        sut.Password.Should().Be("PRODPASS");
        sut.SiteId.Should().Be("002");
    }
}
