// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_UserSession.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_UserSession"/>.
/// Tests session management with timeout tracking and activity updates.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_UserSessionTests
{
    [Fact]
    public void Constructor_SetsLoginAndActivityTimestampsToNow()
    {
        var before = DateTime.Now;
        var sut = new Model_UserSession();
        var after = DateTime.Now;

        sut.LoginTimestamp.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
        sut.LastActivityTimestamp.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void User_CanBeSet()
    {
        var user = new Model_User { EmployeeNumber = 123 };
        var sut = new Model_UserSession { User = user };

        sut.User.Should().Be(user);
    }

    [Fact]
    public void WorkstationName_CanBeSet()
    {
        var sut = new Model_UserSession { WorkstationName = "WS-001" };

        sut.WorkstationName.Should().Be("WS-001");
    }

    [Theory]
    [InlineData("personal_workstation")]
    [InlineData("shared_terminal")]
    public void WorkstationType_CanBeSetToValidTypes(string type)
    {
        var sut = new Model_UserSession { WorkstationType = type };

        sut.WorkstationType.Should().Be(type);
    }

    [Theory]
    [InlineData("windows_auto")]
    [InlineData("pin_login")]
    public void AuthenticationMethod_CanBeSetToValidMethods(string method)
    {
        var sut = new Model_UserSession { AuthenticationMethod = method };

        sut.AuthenticationMethod.Should().Be(method);
    }

    [Fact]
    public void TimeoutDuration_CanBeSet()
    {
        var timeout = TimeSpan.FromMinutes(30);
        var sut = new Model_UserSession { TimeoutDuration = timeout };

        sut.TimeoutDuration.Should().Be(timeout);
    }

    [Fact]
    public void UpdateLastActivity_UpdatesLastActivityTimestamp()
    {
        var sut = new Model_UserSession();
        var originalTimestamp = sut.LastActivityTimestamp;
        
        Thread.Sleep(10);
        sut.UpdateLastActivity();

        sut.LastActivityTimestamp.Should().BeAfter(originalTimestamp);
    }

    [Fact]
    public void TimeSinceLastActivity_ReturnsElapsedTime()
    {
        var sut = new Model_UserSession
        {
            LastActivityTimestamp = DateTime.Now.AddMinutes(-5)
        };

        sut.TimeSinceLastActivity.Should().BeCloseTo(TimeSpan.FromMinutes(5), TimeSpan.FromSeconds(1));
    }

    [Fact]
    public void IsTimedOut_ReturnsFalse_WhenWithinTimeoutDuration()
    {
        var sut = new Model_UserSession
        {
            TimeoutDuration = TimeSpan.FromMinutes(30),
            LastActivityTimestamp = DateTime.Now.AddMinutes(-10)
        };

        sut.IsTimedOut.Should().BeFalse();
    }

    [Fact]
    public void IsTimedOut_ReturnsTrue_WhenExceedsTimeoutDuration()
    {
        var sut = new Model_UserSession
        {
            TimeoutDuration = TimeSpan.FromMinutes(30),
            LastActivityTimestamp = DateTime.Now.AddMinutes(-40)
        };

        sut.IsTimedOut.Should().BeTrue();
    }

    [Fact]
    public void IsTimedOut_ReturnsTrue_WhenEqualToTimeoutDuration()
    {
        var sut = new Model_UserSession
        {
            TimeoutDuration = TimeSpan.FromMinutes(30),
            LastActivityTimestamp = DateTime.Now.AddMinutes(-30)
        };

        sut.IsTimedOut.Should().BeTrue();
    }

    [Fact]
    public void HasErpAccess_ReturnsFalse_WhenUserIsNull()
    {
        var sut = new Model_UserSession { User = null };

        sut.HasErpAccess.Should().BeFalse();
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var user = new Model_User { EmployeeNumber = 123 };
        var loginTime = DateTime.Now.AddMinutes(-10);
        var activityTime = DateTime.Now.AddMinutes(-5);

        var sut = new Model_UserSession
        {
            User = user,
            WorkstationName = "WS-001",
            WorkstationType = "personal_workstation",
            AuthenticationMethod = "windows_auto",
            LoginTimestamp = loginTime,
            LastActivityTimestamp = activityTime,
            TimeoutDuration = TimeSpan.FromMinutes(30)
        };

        sut.User.Should().Be(user);
        sut.WorkstationName.Should().Be("WS-001");
        sut.WorkstationType.Should().Be("personal_workstation");
        sut.AuthenticationMethod.Should().Be("windows_auto");
        sut.LoginTimestamp.Should().Be(loginTime);
        sut.LastActivityTimestamp.Should().Be(activityTime);
        sut.TimeoutDuration.Should().Be(TimeSpan.FromMinutes(30));
    }
}
