// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_AuthenticationResult.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_AuthenticationResult"/>.
/// Tests authentication result model with factory methods.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_AuthenticationResultTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_AuthenticationResult();

        sut.Success.Should().BeFalse();
        sut.User.Should().BeNull();
        sut.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void Success_CanBeSet()
    {
        var sut = new Model_AuthenticationResult
        {
            Success = true
        };

        sut.Success.Should().BeTrue();
    }

    [Fact]
    public void User_CanBeSet()
    {
        var user = new Model_User { EmployeeNumber = 123 };
        var sut = new Model_AuthenticationResult
        {
            User = user
        };

        sut.User.Should().Be(user);
        sut.User!.EmployeeNumber.Should().Be(123);
    }

    [Fact]
    public void ErrorMessage_CanBeSet()
    {
        var sut = new Model_AuthenticationResult
        {
            ErrorMessage = "Test error"
        };

        sut.ErrorMessage.Should().Be("Test error");
    }

    [Fact]
    public void SuccessResult_WithUser_ReturnsSuccessResultWithUser()
    {
        var user = new Model_User { EmployeeNumber = 123, FullName = "Test User" };
        var result = Model_AuthenticationResult.SuccessResult(user);

        result.Success.Should().BeTrue();
        result.User.Should().Be(user);
        result.User!.EmployeeNumber.Should().Be(123);
        result.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void SuccessResult_WithNullUser_ThrowsArgumentNullException()
    {
        var act = () => Model_AuthenticationResult.SuccessResult(null!);

        act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void ErrorResult_WithMessage_ReturnsErrorResultWithMessage()
    {
        var result = Model_AuthenticationResult.ErrorResult("Invalid credentials");

        result.Success.Should().BeFalse();
        result.User.Should().BeNull();
        result.ErrorMessage.Should().Be("Invalid credentials");
    }

    [Fact]
    public void ErrorResult_WithNullMessage_ThrowsArgumentException()
    {
        var act = () => Model_AuthenticationResult.ErrorResult(null!);

        act.Should().Throw<ArgumentException>()
            .WithMessage("Error message cannot be null or whitespace.*");
    }

    [Fact]
    public void ErrorResult_WithEmptyMessage_ThrowsArgumentException()
    {
        var act = () => Model_AuthenticationResult.ErrorResult(string.Empty);

        act.Should().Throw<ArgumentException>()
            .WithMessage("Error message cannot be null or whitespace.*");
    }

    [Fact]
    public void ErrorResult_WithWhitespaceMessage_ThrowsArgumentException()
    {
        var act = () => Model_AuthenticationResult.ErrorResult("   ");

        act.Should().Throw<ArgumentException>()
            .WithMessage("Error message cannot be null or whitespace.*");
    }

    [Fact]
    public void SuccessResult_ThenErrorResult_CreatesIndependentInstances()
    {
        var user = new Model_User { EmployeeNumber = 123 };
        var successResult = Model_AuthenticationResult.SuccessResult(user);
        var errorResult = Model_AuthenticationResult.ErrorResult("Error");

        successResult.Success.Should().BeTrue();
        successResult.User.Should().NotBeNull();
        errorResult.Success.Should().BeFalse();
        errorResult.User.Should().BeNull();
        errorResult.ErrorMessage.Should().Be("Error");
    }
}
