// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Core/Model_HelpContent.cs
// </auto-generated>

using FluentAssertions;
using Material.Icons;
using MTM_Receiving_Application.Module_Core.Models.Core;
using MTM_Receiving_Application.Module_Core.Models.Enums;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_HelpContent"/>.
/// Tests help content model with observable properties and icon conversion.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_HelpContentTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_HelpContent();

        sut.Key.Should().BeEmpty();
        sut.Title.Should().BeEmpty();
        sut.Content.Should().BeEmpty();
        sut.Category.Should().BeEmpty();
        sut.HelpType.Should().Be(Enum_HelpType.Info);
        sut.Icon.Should().Be("HelpCircle");
        sut.Severity.Should().Be(Enum_HelpSeverity.Info);
        sut.RelatedKeys.Should().NotBeNull();
        sut.RelatedKeys.Should().BeEmpty();
        sut.LastUpdated.Should().BeCloseTo(DateTime.Now, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public void Key_CanBeSet()
    {
        var sut = new Model_HelpContent
        {
            Key = "test-help-key"
        };

        sut.Key.Should().Be("test-help-key");
    }

    [Fact]
    public void Title_CanBeSet()
    {
        var sut = new Model_HelpContent
        {
            Title = "Test Help Title"
        };

        sut.Title.Should().Be("Test Help Title");
    }

    [Fact]
    public void Content_CanBeSet()
    {
        var sut = new Model_HelpContent
        {
            Content = "This is test help content."
        };

        sut.Content.Should().Be("This is test help content.");
    }

    [Theory]
    [InlineData(Enum_HelpType.Info)]
    [InlineData(Enum_HelpType.Tip)]
    [InlineData(Enum_HelpType.Warning)]
    [InlineData(Enum_HelpType.Tutorial)]
    public void HelpType_CanBeSetToAllValues(Enum_HelpType helpType)
    {
        var sut = new Model_HelpContent
        {
            HelpType = helpType
        };

        sut.HelpType.Should().Be(helpType);
    }

    [Theory]
    [InlineData(Enum_HelpSeverity.Info)]
    [InlineData(Enum_HelpSeverity.Warning)]
    [InlineData(Enum_HelpSeverity.Critical)]
    public void Severity_CanBeSetToAllValues(Enum_HelpSeverity severity)
    {
        var sut = new Model_HelpContent
        {
            Severity = severity
        };

        sut.Severity.Should().Be(severity);
    }

    [Fact]
    public void IconKind_WithValidIconName_ReturnsParsedKind()
    {
        var sut = new Model_HelpContent
        {
            Icon = "Information"
        };

        sut.IconKind.Should().Be(MaterialIconKind.Information);
    }

    [Fact]
    public void IconKind_WithInvalidIconName_ReturnsDefaultHelpCircle()
    {
        var sut = new Model_HelpContent
        {
            Icon = "InvalidIconName"
        };

        sut.IconKind.Should().Be(MaterialIconKind.HelpCircle);
    }

    [Fact]
    public void IconKind_WithEmptyIcon_ReturnsDefaultHelpCircle()
    {
        var sut = new Model_HelpContent
        {
            Icon = string.Empty
        };

        sut.IconKind.Should().Be(MaterialIconKind.HelpCircle);
    }

    [Fact]
    public void RelatedKeys_CanBePopulated()
    {
        var sut = new Model_HelpContent
        {
            RelatedKeys = new List<string> { "key1", "key2", "key3" }
        };

        sut.RelatedKeys.Should().HaveCount(3);
        sut.RelatedKeys.Should().Contain("key1");
    }

    [Fact]
    public void LastUpdated_CanBeSet()
    {
        var date = new DateTime(2025, 1, 15);
        var sut = new Model_HelpContent
        {
            LastUpdated = date
        };

        sut.LastUpdated.Should().Be(date);
    }

    [Fact]
    public void PropertyChanged_FiresWhenKeyChanges()
    {
        var sut = new Model_HelpContent();
        var eventFired = false;

        sut.PropertyChanged += (s, e) =>
        {
            if (e.PropertyName == nameof(Model_HelpContent.Key))
                eventFired = true;
        };

        sut.Key = "new-key";

        eventFired.Should().BeTrue();
    }
}
