// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_CreateUserResult.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_CreateUserResult"/>.
/// Tests user creation result model with factory methods.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_CreateUserResultTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_CreateUserResult();

        sut.Success.Should().BeFalse();
        sut.EmployeeNumber.Should().Be(0);
        sut.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void Success_CanBeSet()
    {
        var sut = new Model_CreateUserResult { Success = true };

        sut.Success.Should().BeTrue();
    }

    [Fact]
    public void EmployeeNumber_CanBeSet()
    {
        var sut = new Model_CreateUserResult { EmployeeNumber = 12345 };

        sut.EmployeeNumber.Should().Be(12345);
    }

    [Fact]
    public void ErrorMessage_CanBeSet()
    {
        var sut = new Model_CreateUserResult { ErrorMessage = "Test error" };

        sut.ErrorMessage.Should().Be("Test error");
    }

    [Fact]
    public void SuccessResult_WithEmployeeNumber_ReturnsSuccessResult()
    {
        var result = Model_CreateUserResult.SuccessResult(12345);

        result.Success.Should().BeTrue();
        result.EmployeeNumber.Should().Be(12345);
        result.ErrorMessage.Should().BeEmpty();
    }

    [Theory]
    [InlineData(1)]
    [InlineData(999)]
    [InlineData(12345)]
    public void SuccessResult_WithVariousEmployeeNumbers_ReturnsCorrectNumber(int empNum)
    {
        var result = Model_CreateUserResult.SuccessResult(empNum);

        result.Success.Should().BeTrue();
        result.EmployeeNumber.Should().Be(empNum);
    }

    [Fact]
    public void ErrorResult_WithMessage_ReturnsErrorResult()
    {
        var result = Model_CreateUserResult.ErrorResult("User already exists");

        result.Success.Should().BeFalse();
        result.ErrorMessage.Should().Be("User already exists");
        result.EmployeeNumber.Should().Be(0);
    }

    [Fact]
    public void ErrorResult_WithEmptyMessage_PreservesMessage()
    {
        var result = Model_CreateUserResult.ErrorResult(string.Empty);

        result.Success.Should().BeFalse();
        result.ErrorMessage.Should().BeEmpty();
    }

    [Fact]
    public void SuccessResult_ThenErrorResult_CreatesIndependentInstances()
    {
        var successResult = Model_CreateUserResult.SuccessResult(123);
        var errorResult = Model_CreateUserResult.ErrorResult("Error");

        successResult.Success.Should().BeTrue();
        successResult.EmployeeNumber.Should().Be(123);
        errorResult.Success.Should().BeFalse();
        errorResult.ErrorMessage.Should().Be("Error");
        errorResult.EmployeeNumber.Should().Be(0);
    }
}
