// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Core/Model_Dao_Result.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Core;
using MTM_Receiving_Application.Module_Core.Models.Enums;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_Dao_Result"/>.
/// Tests the standardized database operation response object.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_Dao_ResultTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_Dao_Result();

        sut.Success.Should().BeFalse();
        sut.IsSuccess.Should().BeFalse();
        sut.ErrorMessage.Should().BeEmpty();
        sut.Severity.Should().Be(Enum_ErrorSeverity.Info);
        sut.AffectedRows.Should().Be(0);
        sut.ExecutionTimeMs.Should().Be(0);
        sut.ReturnValue.Should().BeNull();
        sut.Exception.Should().BeNull();
    }

    [Fact]
    public void IsSuccess_ReflectsSuccessProperty()
    {
        var sut = new Model_Dao_Result { Success = true };

        sut.IsSuccess.Should().BeTrue();
    }

    [Fact]
    public void Success_WhenTrue_IsSuccessReturnsTrue()
    {
        var sut = new Model_Dao_Result { Success = true };

        sut.IsSuccess.Should().BeTrue();
    }

    [Fact]
    public void Success_WhenFalse_IsSuccessReturnsFalse()
    {
        var sut = new Model_Dao_Result { Success = false };

        sut.IsSuccess.Should().BeFalse();
    }

    [Fact]
    public void ErrorMessage_CanBeSet()
    {
        var sut = new Model_Dao_Result
        {
            ErrorMessage = "Test error message"
        };

        sut.ErrorMessage.Should().Be("Test error message");
    }

    [Theory]
    [InlineData(Enum_ErrorSeverity.Info)]
    [InlineData(Enum_ErrorSeverity.Warning)]
    [InlineData(Enum_ErrorSeverity.Error)]
    [InlineData(Enum_ErrorSeverity.Critical)]
    [InlineData(Enum_ErrorSeverity.Fatal)]
    public void Severity_CanBeSetToAllValues(Enum_ErrorSeverity severity)
    {
        var sut = new Model_Dao_Result
        {
            Severity = severity
        };

        sut.Severity.Should().Be(severity);
    }

    [Fact]
    public void AffectedRows_CanBeSet()
    {
        var sut = new Model_Dao_Result
        {
            AffectedRows = 42
        };

        sut.AffectedRows.Should().Be(42);
    }

    [Fact]
    public void ExecutionTimeMs_CanBeSet()
    {
        var sut = new Model_Dao_Result
        {
            ExecutionTimeMs = 1500
        };

        sut.ExecutionTimeMs.Should().Be(1500);
    }

    [Fact]
    public void ReturnValue_CanBeSet()
    {
        var sut = new Model_Dao_Result
        {
            ReturnValue = 12345
        };

        sut.ReturnValue.Should().Be(12345);
    }

    [Fact]
    public void Exception_CanBeSet()
    {
        var exception = new InvalidOperationException("Test exception");
        var sut = new Model_Dao_Result
        {
            Exception = exception
        };

        sut.Exception.Should().Be(exception);
    }

    [Fact]
    public void CompleteFailureResult_HasAllPropertiesSet()
    {
        var exception = new InvalidOperationException("Test exception");
        var sut = new Model_Dao_Result
        {
            Success = false,
            ErrorMessage = "Operation failed",
            Severity = Enum_ErrorSeverity.Error,
            AffectedRows = 0,
            ExecutionTimeMs = 250,
            Exception = exception
        };

        sut.Success.Should().BeFalse();
        sut.IsSuccess.Should().BeFalse();
        sut.ErrorMessage.Should().Be("Operation failed");
        sut.Severity.Should().Be(Enum_ErrorSeverity.Error);
        sut.AffectedRows.Should().Be(0);
        sut.ExecutionTimeMs.Should().Be(250);
        sut.Exception.Should().Be(exception);
    }

    [Fact]
    public void CompleteSuccessResult_HasAllPropertiesSet()
    {
        var sut = new Model_Dao_Result
        {
            Success = true,
            ErrorMessage = string.Empty,
            AffectedRows = 5,
            ExecutionTimeMs = 100,
            ReturnValue = 123
        };

        sut.Success.Should().BeTrue();
        sut.IsSuccess.Should().BeTrue();
        sut.ErrorMessage.Should().BeEmpty();
        sut.AffectedRows.Should().Be(5);
        sut.ExecutionTimeMs.Should().Be(100);
        sut.ReturnValue.Should().Be(123);
    }
}
