// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Systems/Model_SessionTimedOutEventArgs.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Systems;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_SessionTimedOutEventArgs"/>.
/// Tests session timeout event arguments.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_SessionTimedOutEventArgsTests
{
    [Fact]
    public void Constructor_InheritsFromEventArgs()
    {
        var sut = new Model_SessionTimedOutEventArgs();

        sut.Should().BeAssignableTo<EventArgs>();
    }

    [Fact]
    public void Session_CanBeSet()
    {
        var session = new Model_UserSession();
        var sut = new Model_SessionTimedOutEventArgs { Session = session };

        sut.Session.Should().Be(session);
    }

    [Fact]
    public void IdleDuration_CanBeSet()
    {
        var duration = TimeSpan.FromMinutes(30);
        var sut = new Model_SessionTimedOutEventArgs { IdleDuration = duration };

        sut.IdleDuration.Should().Be(duration);
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var session = new Model_UserSession { WorkstationName = "WS-001" };
        var duration = TimeSpan.FromMinutes(15);

        var sut = new Model_SessionTimedOutEventArgs
        {
            Session = session,
            IdleDuration = duration
        };

        sut.Session.Should().Be(session);
        sut.Session.WorkstationName.Should().Be("WS-001");
        sut.IdleDuration.Should().Be(duration);
    }

    [Fact]
    public void CanBeUsedAsEventArgs()
    {
        var session = new Model_UserSession();
        var duration = TimeSpan.FromMinutes(20);
        var eventArgs = new Model_SessionTimedOutEventArgs
        {
            Session = session,
            IdleDuration = duration
        };

        EventArgs baseArgs = eventArgs;
        baseArgs.Should().BeOfType<Model_SessionTimedOutEventArgs>();
    }
}
