// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/InforVisual/Model_InforVisualPO.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Defaults;
using MTM_Receiving_Application.Module_Core.Models.InforVisual;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_InforVisualPO"/>.
/// Tests Infor Visual purchase order model with observable properties.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_InforVisualPOTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_InforVisualPO();

        sut.PoNumber.Should().BeEmpty();
        sut.PoLine.Should().Be(0);
        sut.PartNumber.Should().BeEmpty();
        sut.PartDescription.Should().BeEmpty();
        sut.OrderedQty.Should().Be(0);
        sut.ReceivedQty.Should().Be(0);
        sut.RemainingQty.Should().Be(0);
        sut.UnitOfMeasure.Should().Be(InforVisualDefaults.DefaultUom);
        sut.DueDate.Should().BeNull();
        sut.VendorCode.Should().BeEmpty();
        sut.VendorName.Should().BeEmpty();
        sut.PoStatus.Should().BeEmpty();
        sut.SiteId.Should().Be(InforVisualDefaults.DefaultSiteId);
    }

    [Fact]
    public void PoNumber_CanBeSet()
    {
        var sut = new Model_InforVisualPO { PoNumber = "PO-123456" };

        sut.PoNumber.Should().Be("PO-123456");
    }

    [Fact]
    public void PoLine_CanBeSet()
    {
        var sut = new Model_InforVisualPO { PoLine = 1 };

        sut.PoLine.Should().Be(1);
    }

    [Fact]
    public void PartNumber_CanBeSet()
    {
        var sut = new Model_InforVisualPO { PartNumber = "PART-001" };

        sut.PartNumber.Should().Be("PART-001");
    }

    [Fact]
    public void PartDescription_CanBeSet()
    {
        var sut = new Model_InforVisualPO { PartDescription = "Test Part Description" };

        sut.PartDescription.Should().Be("Test Part Description");
    }

    [Fact]
    public void OrderedQty_CanBeSet()
    {
        var sut = new Model_InforVisualPO { OrderedQty = 100 };

        sut.OrderedQty.Should().Be(100);
    }

    [Fact]
    public void ReceivedQty_CanBeSet()
    {
        var sut = new Model_InforVisualPO { ReceivedQty = 75 };

        sut.ReceivedQty.Should().Be(75);
    }

    [Fact]
    public void RemainingQty_CanBeSet()
    {
        var sut = new Model_InforVisualPO { RemainingQty = 25 };

        sut.RemainingQty.Should().Be(25);
    }

    [Fact]
    public void UnitOfMeasure_CanBeSet()
    {
        var sut = new Model_InforVisualPO { UnitOfMeasure = "LBS" };

        sut.UnitOfMeasure.Should().Be("LBS");
    }

    [Fact]
    public void DueDate_CanBeSet()
    {
        var date = new DateTime(2025, 2, 1);
        var sut = new Model_InforVisualPO { DueDate = date };

        sut.DueDate.Should().Be(date);
    }

    [Fact]
    public void DueDate_CanBeNull()
    {
        var sut = new Model_InforVisualPO { DueDate = null };

        sut.DueDate.Should().BeNull();
    }

    [Fact]
    public void VendorCode_CanBeSet()
    {
        var sut = new Model_InforVisualPO { VendorCode = "V-001" };

        sut.VendorCode.Should().Be("V-001");
    }

    [Fact]
    public void VendorName_CanBeSet()
    {
        var sut = new Model_InforVisualPO { VendorName = "Acme Corporation" };

        sut.VendorName.Should().Be("Acme Corporation");
    }

    [Theory]
    [InlineData("OPEN")]
    [InlineData("CLOSED")]
    [InlineData("PARTIAL")]
    public void PoStatus_CanBeSetToVariousStatuses(string status)
    {
        var sut = new Model_InforVisualPO { PoStatus = status };

        sut.PoStatus.Should().Be(status);
    }

    [Fact]
    public void SiteId_CanBeSet()
    {
        var sut = new Model_InforVisualPO { SiteId = "SITE-003" };

        sut.SiteId.Should().Be("SITE-003");
    }

    [Fact]
    public void PropertyChanged_FiresWhenPoNumberChanges()
    {
        var sut = new Model_InforVisualPO();
        var eventFired = false;

        sut.PropertyChanged += (s, e) =>
        {
            if (e.PropertyName == nameof(Model_InforVisualPO.PoNumber))
                eventFired = true;
        };

        sut.PoNumber = "PO-NEW";

        eventFired.Should().BeTrue();
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var dueDate = new DateTime(2025, 3, 15);
        var sut = new Model_InforVisualPO
        {
            PoNumber = "PO-789",
            PoLine = 2,
            PartNumber = "PART-XYZ",
            PartDescription = "Widget Assembly",
            OrderedQty = 200,
            ReceivedQty = 150,
            RemainingQty = 50,
            UnitOfMeasure = "EA",
            DueDate = dueDate,
            VendorCode = "V-100",
            VendorName = "Widget Suppliers Inc",
            PoStatus = "PARTIAL",
            SiteId = "002"
        };

        sut.PoNumber.Should().Be("PO-789");
        sut.PoLine.Should().Be(2);
        sut.PartNumber.Should().Be("PART-XYZ");
        sut.PartDescription.Should().Be("Widget Assembly");
        sut.OrderedQty.Should().Be(200);
        sut.ReceivedQty.Should().Be(150);
        sut.RemainingQty.Should().Be(50);
        sut.UnitOfMeasure.Should().Be("EA");
        sut.DueDate.Should().Be(dueDate);
        sut.VendorCode.Should().Be("V-100");
        sut.VendorName.Should().Be("Widget Suppliers Inc");
        sut.PoStatus.Should().Be("PARTIAL");
        sut.SiteId.Should().Be("002");
    }
}
