// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/Reporting/Model_ReportRow.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Models.Reporting;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_ReportRow"/>.
/// Tests unified reporting data structure for all modules.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_ReportRowTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_ReportRow();

        sut.Id.Should().BeEmpty();
        sut.PONumber.Should().BeNull();
        sut.PartNumber.Should().BeNull();
        sut.PartDescription.Should().BeNull();
        sut.Quantity.Should().BeNull();
        sut.WeightLbs.Should().BeNull();
        sut.HeatLotNumber.Should().BeNull();
        sut.CreatedDate.Should().BeCloseTo(default, TimeSpan.FromSeconds(1));
        sut.SourceModule.Should().BeEmpty();
    }

    [Fact]
    public void Id_CanBeSet()
    {
        var sut = new Model_ReportRow { Id = "12345-GUID" };

        sut.Id.Should().Be("12345-GUID");
    }

    [Fact]
    public void PONumber_CanBeSet()
    {
        var sut = new Model_ReportRow { PONumber = "PO-001234" };

        sut.PONumber.Should().Be("PO-001234");
    }

    [Fact]
    public void PartNumber_CanBeSet()
    {
        var sut = new Model_ReportRow { PartNumber = "PART-123" };

        sut.PartNumber.Should().Be("PART-123");
    }

    [Fact]
    public void Quantity_CanBeSet()
    {
        var sut = new Model_ReportRow { Quantity = 100 };

        sut.Quantity.Should().Be(100);
    }

    [Fact]
    public void WeightLbs_CanBeSet()
    {
        var sut = new Model_ReportRow { WeightLbs = 50.5m };

        sut.WeightLbs.Should().Be(50.5m);
    }

    [Theory]
    [InlineData("Receiving")]
    [InlineData("Dunnage")]
    [InlineData("Volvo")]
    public void SourceModule_CanBeSetToValidModules(string module)
    {
        var sut = new Model_ReportRow { SourceModule = module };

        sut.SourceModule.Should().Be(module);
    }

    [Fact]
    public void CreatedDate_CanBeSet()
    {
        var date = new DateTime(2025, 1, 19);
        var sut = new Model_ReportRow { CreatedDate = date };

        sut.CreatedDate.Should().Be(date);
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var date = new DateTime(2025, 1, 19);
        var sut = new Model_ReportRow
        {
            Id = "GUID-123",
            PONumber = "PO-001234",
            PartNumber = "PART-456",
            PartDescription = "Test Part",
            Quantity = 50,
            WeightLbs = 25.5m,
            HeatLotNumber = "HEAT-123/LOT-456",
            CreatedDate = date,
            SourceModule = "Receiving",
            EmployeeNumber = "12345"
        };

        sut.Id.Should().Be("GUID-123");
        sut.PONumber.Should().Be("PO-001234");
        sut.PartNumber.Should().Be("PART-456");
        sut.PartDescription.Should().Be("Test Part");
        sut.Quantity.Should().Be(50);
        sut.WeightLbs.Should().Be(25.5m);
        sut.HeatLotNumber.Should().Be("HEAT-123/LOT-456");
        sut.CreatedDate.Should().Be(date);
        sut.SourceModule.Should().Be("Receiving");
        sut.EmployeeNumber.Should().Be("12345");
    }
}
