// <auto-generated>
// This test file was generated by GitHub Copilot
// Generation Date: 2025-01-19
// Source File: Module_Core/Models/InforVisual/Model_InforVisualPart.cs
// </auto-generated>

using FluentAssertions;
using MTM_Receiving_Application.Module_Core.Defaults;
using MTM_Receiving_Application.Module_Core.Models.InforVisual;
using Xunit;

namespace MTM_Receiving_Application.Tests.Module_Core.Models;

/// <summary>
/// Unit tests for <see cref="Model_InforVisualPart"/>.
/// Tests Infor Visual part model with observable properties.
/// </summary>
[Trait("Category", "Unit")]
[Trait("Layer", "Model")]
[Trait("Module", "Module_Core")]
public class Model_InforVisualPartTests
{
    [Fact]
    public void Constructor_DefaultValues_AreSetCorrectly()
    {
        var sut = new Model_InforVisualPart();

        sut.PartNumber.Should().BeEmpty();
        sut.Description.Should().BeEmpty();
        sut.PartType.Should().BeEmpty();
        sut.UnitCost.Should().Be(0);
        sut.PrimaryUom.Should().Be(InforVisualDefaults.DefaultUom);
        sut.OnHandQty.Should().Be(0);
        sut.AllocatedQty.Should().Be(0);
        sut.AvailableQty.Should().Be(0);
        sut.DefaultSite.Should().Be(InforVisualDefaults.DefaultSiteId);
        sut.PartStatus.Should().Be(InforVisualDefaults.DefaultPartStatus);
        sut.ProductLine.Should().BeEmpty();
    }

    [Fact]
    public void PartNumber_CanBeSet()
    {
        var sut = new Model_InforVisualPart { PartNumber = "PART-001" };

        sut.PartNumber.Should().Be("PART-001");
    }

    [Fact]
    public void Description_CanBeSet()
    {
        var sut = new Model_InforVisualPart { Description = "Test Part Description" };

        sut.Description.Should().Be("Test Part Description");
    }

    [Theory]
    [InlineData("PURCHASED")]
    [InlineData("MANUFACTURED")]
    [InlineData("RAW_MATERIAL")]
    public void PartType_CanBeSetToVariousTypes(string partType)
    {
        var sut = new Model_InforVisualPart { PartType = partType };

        sut.PartType.Should().Be(partType);
    }

    [Theory]
    [InlineData(10.50)]
    [InlineData(100.99)]
    [InlineData(0.01)]
    public void UnitCost_CanBeSet(decimal cost)
    {
        var sut = new Model_InforVisualPart { UnitCost = cost };

        sut.UnitCost.Should().Be(cost);
    }

    [Fact]
    public void PrimaryUom_CanBeSet()
    {
        var sut = new Model_InforVisualPart { PrimaryUom = "LBS" };

        sut.PrimaryUom.Should().Be("LBS");
    }

    [Fact]
    public void OnHandQty_CanBeSet()
    {
        var sut = new Model_InforVisualPart { OnHandQty = 100 };

        sut.OnHandQty.Should().Be(100);
    }

    [Fact]
    public void AllocatedQty_CanBeSet()
    {
        var sut = new Model_InforVisualPart { AllocatedQty = 25 };

        sut.AllocatedQty.Should().Be(25);
    }

    [Fact]
    public void AvailableQty_CanBeSet()
    {
        var sut = new Model_InforVisualPart { AvailableQty = 75 };

        sut.AvailableQty.Should().Be(75);
    }

    [Fact]
    public void DefaultSite_CanBeSet()
    {
        var sut = new Model_InforVisualPart { DefaultSite = "SITE-002" };

        sut.DefaultSite.Should().Be("SITE-002");
    }

    [Theory]
    [InlineData("ACTIVE")]
    [InlineData("OBSOLETE")]
    [InlineData("PENDING")]
    public void PartStatus_CanBeSetToVariousStatuses(string status)
    {
        var sut = new Model_InforVisualPart { PartStatus = status };

        sut.PartStatus.Should().Be(status);
    }

    [Fact]
    public void ProductLine_CanBeSet()
    {
        var sut = new Model_InforVisualPart { ProductLine = "Electronics" };

        sut.ProductLine.Should().Be("Electronics");
    }

    [Fact]
    public void PropertyChanged_FiresWhenPartNumberChanges()
    {
        var sut = new Model_InforVisualPart();
        var eventFired = false;

        sut.PropertyChanged += (s, e) =>
        {
            if (e.PropertyName == nameof(Model_InforVisualPart.PartNumber))
                eventFired = true;
        };

        sut.PartNumber = "NEW-PART";

        eventFired.Should().BeTrue();
    }

    [Fact]
    public void AllProperties_CanBeSetTogether()
    {
        var sut = new Model_InforVisualPart
        {
            PartNumber = "PART-123",
            Description = "Test Part",
            PartType = "PURCHASED",
            UnitCost = 50.00m,
            PrimaryUom = "EA",
            OnHandQty = 100,
            AllocatedQty = 20,
            AvailableQty = 80,
            DefaultSite = "002",
            PartStatus = "ACTIVE",
            ProductLine = "Industrial"
        };

        sut.PartNumber.Should().Be("PART-123");
        sut.Description.Should().Be("Test Part");
        sut.PartType.Should().Be("PURCHASED");
        sut.UnitCost.Should().Be(50.00m);
        sut.PrimaryUom.Should().Be("EA");
        sut.OnHandQty.Should().Be(100);
        sut.AllocatedQty.Should().Be(20);
        sut.AvailableQty.Should().Be(80);
        sut.DefaultSite.Should().Be("002");
        sut.PartStatus.Should().Be("ACTIVE");
        sut.ProductLine.Should().Be("Industrial");
    }
}
