USE `mtm_waitlist`;

CREATE TABLE IF NOT EXISTS `waitlist_active` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `WorkCenter` VARCHAR(50) NOT NULL,
  `RequestType` VARCHAR(100) NOT NULL,
  `Request` VARCHAR(255) NOT NULL,
  `RequestPriority` VARCHAR(20) NOT NULL,
  `MHandler` VARCHAR(100) NOT NULL DEFAULT '',
  `TimeRemaining` DATETIME NOT NULL,
  `RequestTime` DATETIME NOT NULL,
  `StartTime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `AllocatedTime` TIME NULL,
  `PartID` VARCHAR(50) NULL,
  `Operation` VARCHAR(50) NULL,
  `Component1` VARCHAR(50) NULL,
  `Component2` VARCHAR(50) NULL,
  `Component3` VARCHAR(50) NULL,
  `Component4` VARCHAR(50) NULL,
  `Component5` VARCHAR(50) NULL,
  `Component6` VARCHAR(50) NULL,
  `Component7` VARCHAR(50) NULL,
  `Component8` VARCHAR(50) NULL,
  `Component9` VARCHAR(50) NULL,
  `Component10` VARCHAR(50) NULL,
  `Component11` VARCHAR(50) NULL,
  `Component12` VARCHAR(50) NULL,
  `Dunnage` VARCHAR(100) NULL,
  `Skid` VARCHAR(100) NULL,
  `Cardboard` VARCHAR(100) NULL,
  `Boxes` VARCHAR(100) NULL,
  `Other1` VARCHAR(100) NULL,
  `Other2` VARCHAR(100) NULL,
  `Other3` VARCHAR(100) NULL,
  `Other4` VARCHAR(100) NULL,
  `Other5` VARCHAR(100) NULL,
  `PartType` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`),
  KEY `idx_waitlist_active_workcenter` (`WorkCenter`),
  KEY `idx_waitlist_active_requesttime` (`RequestTime`),
  KEY `idx_waitlist_active_part` (`PartID`, `Operation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
